var suggestions = {
    "CV": "özgeçmiş",
    "Kalite": "nitelik",
    "abes": "anlamsız",
    "abide": "anıt",
    "abluka": "kuşatma",
    "abone": "sürdürümcü",
    "acayip": "şaşırtıcı, şaşılası",
    "aceleci": "ivecen, evecen",
    "acil": "geciktirilemez",
    "acizlik": "güçsüzlük, düşkü",
    "adabımuaşeret": "görgü kuralları, davranış töresi",
    "adap": "kurallar, yol, yordam",
    "adaptasyon": "uyarlama",
    "adapte olmak": "uyum sağlamak",
    "adet": "sayı",
    "adeta": "nerdeyse, sanki, sözde, hemen hemen",
    "adi": "bayağı, sıradan",
    "adil": "haktanır",
    "adilane": "hakça, doğrulukla",
    "adli kuvvet": "yargı gücü",
    "adres": "bulunak",
    "afaki": "gereksiz, gelişigüzel",
    "afet": "yıkım, kıran, ölet",
    "afiş": "ası",
    "aforoz": "toplumdışılama",
    "agreman": "uygunluk",
    "agresif": "saldırgan, girişken",
    "agâh": "bilgili",
    "ahali": "topluluk",
    "ahenk": "uyum",
    "ahize": "almaç",
    "ahkâm": "emir, buyruk, yargılar",
    "ahlak": "aktöre, töre",
    "aidat": "ödenti",
    "aidat": "ödenti",
    "aidiyet": "ondanlık, ilişkinlik",
    "aile": "soyocak",
    "ait": "ilgili, ilişkin",
    "ajanda": "andıç, andaç",
    "ajitasyon": "kışkırtma",
    "akabinde": "hemen sonra, ardından",
    "akis": "yankı, tepki",
    "akit": "sözleşme, bağıt, bağlaşma",
    "akli": "ussal",
    "aklıselim": "sağduyu",
    "akreditasyon": "yetkilendirilmiş",
    "akredite": "yetkinleştirilmiş",
    "akreditif": "güven yazısı",
    "aksam": "parçalar",
    "aksan": "söyleyiş, vurgu",
    "aksesuar": "donatımlık",
    "aksetme": "yansıma, yayılma",
    "aksi tesir": "karşıt etki",
    "aksiseda": "yankı",
    "aksiyon": "eylem, edim, devini",
    "aktif": "etken",
    "aktif": "etkin, canlı",
    "aktivasyon": "etkinleştirme",
    "aktivite": "etkinlik",
    "aktüel": "güncül, güncel",
    "akustik": "işitimsel, yankılanım",
    "akıbet": "sonuç, bitim",
    "akıl": "us, bilinç",
    "alaka": "ilgi, ilişik, ilinti",
    "alaka": "ilgi, özen, ilişki, ilinti",
    "alakart": "seçmeli yemek",
    "alamet": "belirti, iz",
    "alarm": "uyarı, uyandırıcı, tetikdur",
    "alaturka": "doğuluca",
    "alelade": "olağan, görülegelen",
    "aleni": "açık, belli, göz önünde",
    "alet": "aygıt",
    "alev": "yalım, yalaz",
    "aleyhtar": "karşıt görüşlü, karşıtçı",
    "aleyhte söyleme": "dil uzatma, kötüleme",
    "alfabe": "abece",
    "alternatif": "dalgalı akım, seçenek",
    "ama": "ancak",
    "amade": "hazır",
    "amatör": "özengen",
    "ambale olmak": "başı şişmek",
    "ambargo": "engelti, engelleyim",
    "amblem": "belirtke, simge, imlem",
    "ambülans": "cankurtaran",
    "amenna": "inandık, öyle olsun",
    "amir": "buyuran",
    "amiyane": "sıradan, bayağıca",
    "amme": "kamu",
    "amortisman": "aşınım, aşınmalık",
    "amplifikatör": "yükselteç",
    "an": "kıpı, sürem",
    "anahtar": "açkı açar",
    "analitik": "çözümsel",
    "analiz": "çözümleme",
    "anane": "gelenek",
    "anarşi": "başsızlık, kargaşa",
    "anatomi": "gövdebilim, içyapı",
    "anbean": "gitgide",
    "anekdot": "öykücük, öykümce, kısa anlatı",
    "anestezi": "duyum yitimi, uyuşturma, duyumsuzlaştırma",
    "angaje olmak": "bağlantı yapmak",
    "angarya": "yüklenti",
    "ani": "birdenbire",
    "animasyon": "canlandırma, öykünleme",
    "anket": "sormaca",
    "anonim": "ortaklaşa",
    "anons": "duyuru",
    "anormal": "olağandışı",
    "anormal": "olağandışı",
    "ansiklopedi": "bilgilik",
    "antant": "anlaşma",
    "antet": "başlık",
    "antifriz": "donmaönler",
    "antik": "eskil",
    "antipati": "sevimsizlik, iticilik, karşıtduygu",
    "antitez": "karşısav",
    "antre": "giriş",
    "antrenman": "çalışım",
    "antrenör": "çalıştırıcı",
    "antrepo": "arakoruncak",
    "antrparantez": "ayraç içinde, söz arası",
    "anında": "sırasında",
    "aperitif": "öniçki",
    "apolet": "omuzluk",
    "ar": "utanma",
    "aranje etmek": "uyarlamak",
    "araz": "belirti, iz",
    "arazi": "yerey",
    "ardiye": "yığımlık",
    "argüman": "tanıt, kanıt",
    "ari": "arınmış",
    "aristokrasi": "soylular yönetimi",
    "aritmetik": "sayıbilgisi",
    "arkeoloji": "kazıbilim",
    "armada": "donanma",
    "armatür": "donatı",
    "armağan": "ödül",
    "armoni": "uyum",
    "arsız": "utanmaz",
    "arz": "sunu, yeryüzü",
    "arz-talep": "sunu-istem",
    "arzu": "istek",
    "arzuhal": "dilekçe",
    "arıza": "bozukluk, aksama",
    "arşiv": "belgelik",
    "as": "gözde",
    "asalet": "soyluluk, aksoy",
    "asamble": "toplantı, kurul",
    "asansör": "inerçıkar",
    "asayiş": "güvenlik",
    "asgari müşterek": "altbileşen",
    "asgari": "en az, en düşük",
    "asi": "başkaldıran",
    "asil": "soylu",
    "asimile": "özümleme, eritme, benzeştirme",
    "aslen": "kökten, soyca",
    "asli": "birincil, köklü",
    "aspiratör": "koku çeker, emeç, emmeç",
    "asri": "çağdaş, çağcıl",
    "astronomi": "gökbilim",
    "astronomik": "kavranamaz, abartık",
    "asıl": "kök, kaynak, gerçek",
    "asır": "yüzyıl",
    "atalet": "üşengenlik, durgunluk, işlemezlik",
    "ateist": "tanrıtanımazlık",
    "atölye": "işlik",
    "avans": "önödeme, önakça",
    "avantaj": "üstünlük, çıkar, yarar, elverişlilik",
    "averaj": "ortalama, sayı farkı",
    "avukat": "savunman",
    "ayan beyan": "apaçık, açık seçik",
    "ayin": "tapım, tapınma",
    "aynen": "olduğu gibi, tıpatıp",
    "aynı": "tıpkısı, özdeş",
    "ayıp": "utanç verici",
    "aza": "üye",
    "azami": "en çok, en yüksek",
    "azim": "direnç, istenç, kesin karar",
    "aşağılık kompleksi": "altsanma",
    "aşikâr": "apaçık",
    "aşina": "bildik, tanıdık",
    "aşk": "sevi",
    "badire": "sıkıntı, darboğaz",
    "bagaj": "taşıncak, yolcu yükü",
    "bahane": "nedensi, sözde neden",
    "bahar": "ilkyaz",
    "bahis mevzusu": "söz konusu",
    "bahsetme": "söz etme, değinme",
    "bahsetmek": "söz etmek",
    "baht": "yazgı",
    "bahtiyar": "mutlu",
    "bahtlı": "akyazılı",
    "bahtsız": "karayazılı",
    "bakir": "eldeğmemiş",
    "bakiye": "geri kalan, kalanca",
    "balans": "denge",
    "bandrol": "denetim pulu, vergilendi",
    "banliyö": "dolay, yörekent",
    "banyo": "yunak",
    "baraj": "büvet, engel",
    "bariyer": "yol korumalığı, engel, önleç",
    "bariz": "açık, belirgin",
    "basiret": "uzgörü, seziş",
    "basit": "sıradan, kolay, yalın",
    "baskül": "ağırtartaç",
    "batıl itikat": "boşinanış",
    "batıl": "gerçek karşıtı, boş",
    "bay bay": "güle güle, hoşça kal",
    "bazen": "arasıra, kimileyin",
    "bazı": "kimi",
    "bedbaht": "mutsuz",
    "beddua etme": "ilenme",
    "beddua": "ilenç",
    "bedel": "karşılık, tutar",
    "bedeni": "tensel",
    "bedhah": "kötücül",
    "bekap": "yedekleme",
    "bekgraund": "artalan, artyetişim",
    "bekâr": "evlenmemiş",
    "bekâret": "erdenlik",
    "belediye": "yerel yönetim",
    "belki": "umulur",
    "bent": "küçük büğet, yasa altbölümü",
    "beraat": "benzerlerinden üstün",
    "berabere": "başa baş",
    "beraet": "ilişiksiz çıkma, aklanma",
    "berat": "san belgesi",
    "bereket": "bolluk, ürek, artağanlık",
    "berrak": "duru",
    "bertaraf etmek": "gidermek, ortadan kaldırmak",
    "beste": "ezgi",
    "beyan": "bildirim, diyev",
    "beyanat": "demeç",
    "beyanat": "demeç, bildiri",
    "beyanname": "bildiri, bildirge",
    "beyhude": "boşuna, boşyere",
    "beynelmilel": "uluslararası",
    "biat etmek": "koşulsuz boyun eğiş",
    "biblo": "süslük",
    "bila": "-sız",
    "bilahare": "sonradan",
    "bilakis": "tam eksine, tersine",
    "bilanço": "dengelem",
    "bilbord": "duyuru tahtası, duyuraç",
    "bilhassa": "hele, özellikle, öncelikle",
    "bilmukabele": "ben de, karşılık olarak",
    "bilumum": "hepsi, toptan, hep, bütün",
    "binaen": "dayanılarak, -den dolayı",
    "binaenaleyh": "bu yüzden, bundan ötürü",
    "bitap": "bitkin, argın",
    "bitaraf": "yansız, çekimser",
    "biyografi": "yaşamöyküsü, özgeçmiş",
    "bizzat": "özkendisi",
    "biçare": "umarsız",
    "bloke": "bekletileme",
    "blöf": "ürkütüm, ürkütmece",
    "bonkör": "eliaçık",
    "bono": "ödencek",
    "bonservis": "iyi çalıştı belgesi",
    "boykot": "direniş",
    "branç": "kuşluk yemeği",
    "branş": "dal, kol, bölüm",
    "brifing": "özetlem, bilgilendirme",
    "brüt": "kesintisiz",
    "bu cihetle": "bu nedenle",
    "bu suretle": "böylece, böylelikle",
    "buldozer": "yoldüzler",
    "bulüğ": "ergenlik",
    "burjuva": "kentsoylu",
    "burs": "öğrenimlik",
    "buse": "öpme, öpücük",
    "butlan": "geçersizlik",
    "buton": "düğme",
    "bütçe": "geçinge",
    "cadde": "anayol",
    "cahil": "bilisiz, okumamış, görgüsüz",
    "caiz": "olabilir, uygun",
    "camia": "topluluk",
    "canhıraş": "yürek parçalayıcı",
    "cani": "kıyıcı",
    "cari": "yürürlükte olan",
    "cazibe": "çekicilik, albeni",
    "cebren": "güç kullanarak",
    "cefa": "üzgü",
    "cehalet": "bilmezlik",
    "celp": "getirtme, çağırma",
    "celpname": "geldiri, çağırma belgesi",
    "celse": "oturum",
    "cemaat": "dinsel topluluk",
    "cemiyet": "toplum, kurum, dernek",
    "cendere": "baskı",
    "cengâver": "savaşcı",
    "cenin": "dölüt, döl",
    "center": "merkez",
    "centilmen": "görgülü",
    "cephe": "önyüz, savaş bölgesi",
    "cereyan etmek": "olagelmek",
    "cereyan": "akım, akıntı",
    "cerrah": "yarman",
    "cesaret": "yüreklilik",
    "cesur": "gözüpek, yürekli",
    "cet": "ata",
    "cetvel": "çizelge",
    "cevap": "yanıt",
    "cevap": "yanıt",
    "cevval": "kıpırdak, devingen",
    "cezaevi": "tutukevi, suçlularevi",
    "cezbetme": "çekme, etkileme",
    "cidden": "gerçekten",
    "ciddi": "ağırbaşlı",
    "ciddiye alma": "gerçek sanma, inanma",
    "cihan": "evren",
    "cihat": "din uğruna savaşma",
    "cihaz": "aygıt",
    "cimri": "elisıkı",
    "cinayet": "öldürü, cana kıyma",
    "cinnet": "çılgınlık",
    "cins": "eşey, soy, çeşit",
    "ciro": "çevirim, aktarım",
    "civar": "yöre, dolay, çevre",
    "cömert": "eliaçık",
    "cümle": "tümce, tüm",
    "cüretkâr": "atak, kendini bilmez",
    "cürmü meşhut": "suçüstü",
    "cürüm": "suç",
    "cüzi": "pek az",
    "dahi": "bile",
    "dahil": "iç, içeri, içerde, içinde",
    "dahili nizamname": "içtüzük",
    "daima": "sürekli, sürgit",
    "dair": "değgin, ilişkin",
    "dalalet": "sapınç, sapkınlık",
    "damping": "düşürüm",
    "darp": "çarpma, vurma",
    "davet": "çağrı",
    "davet": "çağrı",
    "davetiye": "çağrılık",
    "dedektör": "arayıcı, bulucu aygıt",
    "defa": "kez",
    "defans": "savunma",
    "defetme": "savma, savuşturma",
    "defile": "giysi (giyim) gösterisi",
    "defin": "gömülme",
    "define": "gömü",
    "deforme": "değişme, bozulma",
    "dehşet": "yılgı",
    "dejenere": "yozlaşma, bozulma, çığrından çıkma",
    "deklarasyon": "açıklama, bildiri",
    "dekont": "akça belgesi",
    "delalet": "aracılık, yol gösterme",
    "delil": "kılavuz, kanıt, tutamak",
    "demagog": "söz ebesi",
    "demagoji": "halkavcılığı",
    "demokrasi": "halkerki",
    "demoralize": "içgücü yitikliği",
    "denli": "kadar",
    "depar": "çıkış",
    "departman": "bölüm",
    "depo": "koruncak",
    "depozito": "ilkakça, önödence",
    "depresyon": "çöküntü",
    "ders": "öğrence",
    "dert": "tasa, kaygı",
    "despot": "buyurgan",
    "destan": "koçaklama",
    "detay": "ayrıntı",
    "detay": "ayrıntı",
    "deterjan": "arıtıcı",
    "detone": "aykırı düşme",
    "deva": "umar",
    "devalüasyon": "değer düşürümü",
    "devamı": "süreği",
    "devriye": "gezge",
    "dezavantaj": "yarar yitirimi, elverişsizlik",
    "deşifre": "gizi çözülmüş",
    "didaktik": "öğretici",
    "dijital": "sayısal",
    "dikkat": "özeni, özen",
    "diksiyon": "söyleyiş biçimi, demece, söylem",
    "diktatör": "zorba, buyurgan",
    "dimağ": "beyin",
    "dinamik": "devingen, devimsel",
    "dinamik": "devingen, etkin, canlı",
    "dinamizm": "çalışma gücü",
    "dipfriz": "donduraç",
    "diploma": "bitirdi belgesi",
    "dirayet": "başarıcılık, beceriklilik",
    "direkt": "dolaysız",
    "direktif": "buyruk",
    "direktör": "yönetici, yönetmen",
    "disiplin": "düzenbağı, düzence",
    "diskalifiye": "yarışdışı",
    "distribütör": "dağıtımcı",
    "diyagram": "çizenek, çizge",
    "diyalekt": "lehçe",
    "diyalektik": "eytişim, eytişimsel",
    "diyalog": "söyleşme, söyleşim",
    "diyapozitif": "yansı",
    "diyet": "besidüzen, besibilim, karşılık",
    "dizayn": "tasarım",
    "dizayn": "tasarım, tasarçizim",
    "diğer": "öteki, başka, öbürü",
    "doktor": "canbakan, sağın",
    "doktrin": "öğreti",
    "doküman": "belge",
    "doküman": "belge",
    "dolayısıyla": "bundan ötürü",
    "dominant": "baskın, başat",
    "drahoma": "oğlanbaşlığı",
    "dram": "üzgü, üzünç",
    "dramatik": "üzgüsel",
    "dua": "yakarı, yakarma, yakarış",
    "duayen": "deneyimli, yaşlı öncü",
    "dublaj": "seslendirme",
    "dâhi": "üstüninsan",
    "dükkân": "satış yeri",
    "dünya": "acun, yeryuvar",
    "dürbün": "uzakgörür",
    "düstur": "ilke, genel kural",
    "düşman": "yağı",
    "e-mail": "elektronik posta, ileti, el-mek",
    "ebat": "boyut",
    "ebedi": "sonsuz, sonrasız, ölümsüz",
    "ebediyen": "sonsuza değin",
    "ebediyet": "ölümsüzlük",
    "ebeveyn": "ana ile baba",
    "ecdat": "atalar",
    "eda": "yerine getirme, biçem",
    "edebiyat": "yazın, akyazın, aryazın",
    "edilgin": "etkisiz, devinimsiz",
    "editör": "yayımcı",
    "efekt": "sesleme, ses sandırma",
    "efkâr": "fikirler, tasa, kaygı",
    "efor": "özgüç, çaba",
    "efsane": "söylence",
    "egale": "rekor eşitleme",
    "ego": "benlik",
    "egzersiz": "alıştırma",
    "egzotik": "özgünel",
    "ehemmiyet": "önem",
    "ehliyet": "yeterlik",
    "ekol": "çığır",
    "ekoloji": "çevrebilim",
    "ekonomi": "tutumbilim, varlıkbilim",
    "ekran": "görüntülük, akcam",
    "ekspertiz": "bilirkişi",
    "ekstre": "hesap özeti",
    "ekstrem": "aşırı, uç",
    "elbet": "eninde sonunda",
    "elbette": "kuşkusuz, eninde sonunda",
    "elbise": "giysiler",
    "elem": "kaygı",
    "elim": "acınacak",
    "elit": "seçkin",
    "elveda": "esen kalın",
    "elzem": "çok gerekli",
    "emanet": "korumaya bırakılan",
    "emare": "belirti, iz",
    "emir": "buyruk",
    "emlak": "taşınmazmallar",
    "empati": "duygudaşlık",
    "emperyalist": "yayılmacı, sömürgeci",
    "empoze etme": "dayatma",
    "emrivaki": "olup bitti",
    "emsal": "benzerler",
    "endeks": "dizin",
    "endeksleme": "ilişkilendirme",
    "endişe": "tasa, kaygı, kuşku",
    "endoskopi": "içgürüm, içgörü",
    "endüstri": "işleyim",
    "enkaz": "yıkıntı",
    "enstrümental": "çalgısal",
    "entelektüel": "aydın",
    "enteresan": "ilginç",
    "enteresan": "ilginç, ilgi çekici",
    "entrika": "düzence, dolantı",
    "envanter": "döküm, sayım",
    "epik": "yiğitsel",
    "erbap": "bilgiç",
    "ergonomi": "işbilimi",
    "ergonomik": "işe uygun",
    "erkân": "ileri gelenler, kurallar",
    "erozyon": "aşınma, toprak yitimi",
    "esaret": "boyunduruk, tutsaklık",
    "esasen": "doğrusu",
    "eser": "yapıt, yaratı",
    "esir": "tutsak",
    "eskiz": "taslak",
    "eskort": "koruma aracı",
    "esrar": "giz, gizem",
    "estağfurullah": "bir şey değil",
    "estetik": "güzelduyu",
    "etik": "töre bilimi, törel, aktöresel",
    "etiket": "ederce",
    "etken": "etki, etmen, neden",
    "etkin": "devinimli, işleyen",
    "etnik": "budunsal",
    "etüt": "ön çalışma",
    "evham": "kuruntu, sanı",
    "evvela": "ilkönce, başlangıçta",
    "evvelce": "önceleri",
    "evveliyat": "öncesi",
    "ezeli": "öncesiz",
    "ezkaza": "bilmeyerek",
    "eşantiyon": "örneklik",
    "eşkâl": "biçim, kılık, görünüş, tanım",
    "faaliyet": "çalışma, etkinlik, edim",
    "fahiş": "aşırı, ölçüdışı",
    "fahri": "karşılıksız",
    "fail": "yapan, eden, edimci",
    "faiz": "ürem",
    "fakat": "yalnız, ancak",
    "fakir": "yoksul",
    "fakir": "yoksul",
    "faks": "belgegeçer",
    "faktör": "etken",
    "fanatik": "bağnaz",
    "fani": "kalımsız, ölümlü",
    "fantezi": "düşlem, düşsü",
    "faraza": "diyelim ki, sözgelimi",
    "fark etmek": "ayrımsamak",
    "fark": "ayrım",
    "fark": "ayırtı, başkalık",
    "farkına varılma": "ayrımsanma",
    "farz etme": "varsayma",
    "fatura": "satımca",
    "faul": "kuraldışı",
    "fay": "kırık",
    "fayans": "sırlıtaş",
    "fayda": "yarar",
    "fayda": "yarar",
    "fazilet": "erdem",
    "feda": "gözden çıkarma",
    "fedai": "gönüllü",
    "fedakâr": "esirgemez, özverili",
    "fedakârlık": "özveri",
    "federasyon": "üstbirlik",
    "fenomen": "olay, görüngü",
    "feragat": "elçekme, özgeçi, vazgeçme",
    "ferah": "iç açıcı",
    "feribot": "taşıt gemisi",
    "fert": "birey",
    "fesat": "bozut, bozguncu",
    "fast-food": "ivedi yemek, ayaküstü",
    "feveran": "coşma, kabarma",
    "fevkalade": "olağanüstü",
    "fezleke": "sorgu özeti",
    "fidye": "kurtulmalık",
    "fihrist": "dizin",
    "fiil": "edim, eylem, yüklem",
    "fikir": "düşün, düşünü",
    "fikri sabit": "saplantı",
    "fikri": "düşünsel",
    "fiks menü": "tek liste",
    "final": "bitiş, bitim, sonlama",
    "finanse etmek": "akçalamak",
    "finiş": "varış, bitiş",
    "firari": "kaçak, kaçkın",
    "fire": "eksinti",
    "fitne": "arabozma",
    "fiyasko": "başarısızlıkla sonuçlanan",
    "fiyat": "eder",
    "fizibilite": "uygulanabilirlik, yapılabilirlik",
    "fiş": "girgi",
    "flaş disk": "çubuk bellek, belgetaşır",
    "flaş": "gözalıcı",
    "flora": "bitey, bitki varlığı",
    "flu": "bulanık",
    "flört": "duygusal ilişki",
    "fobi": "korku, korkuntu",
    "folklor": "halkbilim, halkoyunu, halk yaratması",
    "fon": "kaynak, arka yüz",
    "fonksiyon": "işlev",
    "formalite": "gerekli işlem",
    "formasyon": "biçimlenme eğitimi, yetişim, biçimleyim",
    "forum": "toplu tartışma",
    "fotokopi": "izçekim, tıpkıçekim",
    "fragman": "tanıtı",
    "fraksiyon": "bölüngü",
    "frapan": "göze çarpan",
    "fren": "durduraç",
    "frenlemek": "gemvurmak",
    "frişop": "gümrüksüz satış yeri",
    "fundamentalist": "köktendinci",
    "futbol": "ayaktopu",
    "fuzuli": "gereksiz",
    "fütursuz": "korkusuz, umursamaz",
    "fıkra": "bölümcük, öykücük, güldüşün",
    "fırka": "tümen",
    "gaddar": "acımasız",
    "gafil": "aymaz",
    "gaflet": "boş bulunma, dalgı, aymazlık",
    "gaile": "sıkıntı, kaygı",
    "gaip": "kayıp, yok olmuş",
    "gala": "ilk gösterim, öngösterim",
    "galaksi": "gökada",
    "galat": "büyük yanlış",
    "galeri": "sergievi",
    "galeyan": "coşma, kaynama",
    "galiba": "belki, görünüşe göre",
    "galibiyet": "yengi",
    "gam": "tasa, kaygı",
    "gani": "varsıl",
    "ganimet": "emeksiz kazanç",
    "garabet": "tuhaflık, şaşırtıcılık",
    "garaj": "taşıtlık",
    "garanti": "güvence",
    "garanti": "güvence",
    "garaz / garez": "gizli düşmanlık, kötü istek",
    "gardırop": "giysilik",
    "garipseme": "yadırgama",
    "garnitür": "yanlık, bezenti",
    "gasp": "kapma, zorla alma",
    "gaye": "erek",
    "gayret": "çaba",
    "gayri safi hasılat": "tümgelir",
    "gayrimenkul": "taşınmazmal",
    "gayrı ihtiyari": "elimde olmadan, istemeyerek",
    "gaza": "din uğruna savaş",
    "gazap": "öfke",
    "genelde": "çoğunca",
    "genetik": "kalıtımsal, soyaçekim",
    "girdap": "burgaç",
    "global": "küresel, bütünsel",
    "grafik": "çizge",
    "gramer": "dilbilgisi",
    "grev": "işbırakımı",
    "gril": "ızgara",
    "grup": "öbek, küme",
    "gurbet": "yadel",
    "gurbetçi": "elgin",
    "gurme": "tatbilir",
    "gurur": "övünç",
    "güruh": "kalabalık",
    "güya": "sanki, sözde",
    "güz": "sonbahar",
    "güzergâh": "uğrak, geçek, geçiyolu",
    "güzide": "seçkin",
    "gıda": "besin",
    "gıpta": "imrenme, imrenti",
    "gıyap": "yokluk, yitiklik",
    "gıybet": "çekiştirme",
    "haber": "duyum, duyut",
    "haberci": "ulak",
    "haberleşme": "iletişim",
    "habis": "kötücü",
    "hacet": "gereksinim, gerekli",
    "hacim": "oylum",
    "haciz": "elkoyma",
    "hafriyat": "kazı",
    "hafıza": "anımsama yetisi, bellek",
    "haiz": "sahip, taşıyan",
    "hak": "adalet, doğruluk, pay",
    "hakaret": "küçük düşürme, aşağılama",
    "hakikat": "gerçek",
    "hakimiyet": "üstünlük, egemenlik",
    "hal": "toptan gıda satış merkezi",
    "halaskâr": "kurtarıcı",
    "halbuki": "meğer, oysa",
    "halef": "ardıl",
    "halef": "yerine geçen, ardıl",
    "halel": "bozma, sarsma, gölge düşürme",
    "halis": "katışıksız",
    "halüsinasyon": "varsanı, sanrı",
    "hamam": "yunak",
    "hami": "koruyan, gözeten",
    "hamile": "gebe",
    "hamiyet": "iyilikseverlik",
    "hamle": "saldırı, atılış",
    "handikap": "engel, elverişsiz durum",
    "hanedan": "soy",
    "harabe": "ören, yıkı, yıkıntı",
    "hareket": "devim, devinim",
    "hareket": "devinim",
    "hareketli": "devingen",
    "harekât": "eylemce",
    "harf": "yazaç, imce",
    "harika": "olağanüstü",
    "haris": "açgözlü",
    "hariç": "dışarı, dışta",
    "has": "arı, özgü",
    "haset": "kıskançlık, çekemezlik",
    "hasret": "özlem",
    "hassas": "duygulu, duyarlı",
    "hasta": "sayrı",
    "hasıl": "oluşan, türeyen",
    "hasılat": "kazanç, verim, ürün",
    "hasılı": "kısacası",
    "hasım": "düşman, karşı taraf",
    "hata": "yanlış, yanılgı",
    "hatip": "söylevci",
    "hatta": "üstelik, bile, dahası, öyle ki",
    "hatıra defteri": "günce",
    "hatıra": "anı, andaç",
    "hatırlama": "ansıma, anımsama",
    "hatırşinas": "gönülalıcı, saygılı",
    "havale etmek": "göçermek",
    "havali": "yöre, çevre",
    "hayal meyal": "belli belirsiz",
    "hayal": "düş, imge",
    "hayal": "düş, sanı",
    "hayali": "imgesel, düşsel",
    "hayat": "yaşam",
    "hayat": "yaşam, dirim",
    "hayati": "yaşamsal",
    "hayli": "oldukça, epey",
    "hayran": "tutkun",
    "hayret": "şaşkı",
    "hayâ": "utanma",
    "hayıflanma": "acınma, yerinme",
    "hazan": "sonyaz, güz",
    "hazin": "dokunaklı, acıklı",
    "hazine": "gömü",
    "hazım": "sindirme",
    "haşmet": "yücelik, görkem",
    "hece": "seslem",
    "hedef": "erek, amaç",
    "hediye": "armağan",
    "hekim": "sağın",
    "helezon": "sarmal",
    "helikopter": "dönerkanat",
    "hem de": "üstelik",
    "hemcins": "türdeş",
    "hemen": "duraksamadan",
    "hemfikir": "oydaş, düşündeş",
    "hemzemin": "düzeydeş",
    "hemşeri": "ildeş, kentteş",
    "hentbol": "eltopu",
    "henüz": "ancak, daha, şimdiye dek",
    "hercai": "gelgeç",
    "herze": "boşsöz",
    "heterojen": "ayrışık",
    "heves": "özenti",
    "heyelan": "toprak kayması, göçü",
    "heyet": "kurul",
    "heyhat": "yitiğe yazıklanma",
    "heykel": "yontu",
    "hezeyan": "saçma sapan konuşma, sayıklama",
    "hezimet": "bozgun",
    "hicap": "utanç",
    "hiciv": "yergi, taşlama",
    "hicran": "ayrılık, unutulmaz acı",
    "hijyenik": "sağlıksal",
    "hikaye": "öykü",
    "hikâye": "öykü",
    "hikâye": "öykü",
    "hile": "aldatı, aldaç",
    "himaye": "gözetim",
    "hipotez": "varsayım",
    "his": "duygu, sezgi",
    "hisse": "pay",
    "hissedar": "paydaş, bölüşümcü",
    "hissetme": "sezinleme, duyumsama",
    "hissetmek": "duymak, sezmek, duyumsamak",
    "hissi": "duygusal",
    "hissikablelvuku": "önsezi",
    "hit": "önde, ünlenmiş",
    "hitap": "seslenme, eyitiş, eyitme",
    "hiyerarşi": "sıradüzen",
    "hizip": "bölek",
    "hobi": "dinlendirici uğraş, düşkü",
    "holigan": "karmaşacı",
    "homojen": "bağdaşık, benzeşik, türdeş",
    "hoparlör": "sesyayar, sesyükseltici",
    "hukuk": "tüze",
    "hummalı": "yoğun",
    "hunhar": "kan dökücü",
    "hurafe": "boşinan, boşinanç",
    "hurşit": "güneş",
    "husumet": "karşıtlık, düşmanlık",
    "husus": "konu",
    "hususiyet": "özellik",
    "huy": "alışkı",
    "huzur": "erinç, dirlik",
    "hâkim": "egemen, üstün, yüksek, yaygın, yargıç",
    "hâl": "durum, bulunuş",
    "hâlen": "şimdi, şimdilik",
    "hâlâ": "şimdiye dek, bugün de, şimdi bile",
    "hücre": "göze",
    "hükmi şahıs": "tüzelkişi",
    "hükümsüz": "geçersiz",
    "hülasa": "kısaca, özetleme",
    "hümanist": "insancıl",
    "hüner": "beceri",
    "hür": "özgür",
    "hüsran": "düşyıkımı",
    "hüzün": "üzgü",
    "hırs": "doymazlık, açgözlülük",
    "hışım": "öfke",
    "iade": "geri gönderme",
    "ibadet": "tapınma, tapım",
    "ibare": "sözce, deyiş",
    "ibraz": "gösterme",
    "ibret alma": "örnek alma",
    "ibret": "öğrenek",
    "icap": "gereklik",
    "icat": "buluş, türeti",
    "icazet": "bitirdi belgesi, izin, onay",
    "icmal": "genel toplam",
    "icra": "edim",
    "idame": "sürdürme",
    "idareyi maslahat": "geçiştirme, oluruna bağlama",
    "idari": "yönetsel",
    "iddia": "sav",
    "iddianame": "savca",
    "ideoloji": "öğreti, düşüngü",
    "idman": "alıştırma",
    "idol": "tapınca",
    "idrak": "algı, alımlama",
    "ifa": "ödeme, yerine getirme",
    "ifade": "anlatım, anlatış, söylem",
    "iflah olma": "onma, kurtulma",
    "iflas": "tükenme, batkı",
    "iftihar": "övünç, kıvanç",
    "iftira": "karaçalma, karalama",
    "ifşa": "açığa vurma, dile verme",
    "ihale": "eksiltme",
    "ihanet": "aldatma",
    "ihbar": "bildirme",
    "ihbarname": "bildirim",
    "ihlal": "çiğnem",
    "ihmal": "boşlama, savsaklama",
    "ihracat": "dışsatım",
    "ihtar": "uyarı",
    "ihtilaf": "anlaşmazlık, uyuşmazlık",
    "ihtimal": "olabilirlik, olasılık",
    "ihtimal": "olasılık",
    "ihtimam": "özen gösterme",
    "ihtiras": "tutku, gözüdoymazlık",
    "ihtiva": "içerme, kapsama",
    "ihtiyari": "isteğe bağlı",
    "ihtiyat": "yedek, sakınma",
    "ihtiyaç": "gereksinim",
    "ihtiyaç": "gereksinim, gerekseme",
    "ihtişam": "görkem, gözalıcılık",
    "ihya": "canlandırma, diriltme, mutlu kılma",
    "ikame": "yerine koyma",
    "ikametgâh ilmühaberi": "oturma belgesi",
    "ikametgah ilmuhaberi": "oturma belgesi",
    "ikametgâh": "yerleşim yeri, konut",
    "ikametgah": "yerleşim yeri, konut",
    "ikaz": "uyarı",
    "ikmal": "bütünleme, tümleme",
    "ikna": "inandırma",
    "ikon": "simge",
    "ikrar": "kabul etme",
    "iktidar": "yönetim erki",
    "iktisat": "tutumbilim",
    "ilahi": "tanrısal, tapuğ",
    "ilahiyat": "tanrıbilim",
    "ilam": "yargı bildirisi",
    "ilan": "duyuru",
    "ilelebet": "sonsuza dek, sürgit",
    "ilhak": "katma",
    "ilham": "esin",
    "ilham": "esin, esinlenme, içe doğma",
    "ilkbahar": "ilkyaz",
    "illegal": "yasadışı",
    "illüzyon": "yanılsama",
    "illüzyonist": "gözbağcı",
    "ilmühaber": "durum belgesi",
    "iltica": "sığınma",
    "iltihak": "katılma",
    "iltimas": "kayırma",
    "ima": "anıştırma, sezdirme, dokundurma",
    "imaj": "imge",
    "imalat ": "yapım",
    "imalı": "üstü örtülü",
    "iman": "inanç",
    "imkan": "olanak",
    "imkân": "olanak",
    "imkân": "olanak",
    "imla": "yazım",
    "import": "dışalım",
    "imtihan": "sınav",
    "imtina": "çekinme, kaçınma",
    "imtiyaz": "ayrıcalık",
    "inat": "direni, direnim",
    "inatçı": "direngen",
    "indeks": "dizin",
    "infaz": "yerine getirme, yürütüm",
    "infial": "gücenme, içerleme",
    "inisiyatif": "öngüdü, öncelik, öncecilik, üstünlük",
    "inkâr": "yadsıma, yoksama",
    "inkılap": "devrim",
    "inovasyon": "yenilikçilik, yenileşim",
    "input": "girdi",
    "insani": "insancıl",
    "integral": "tümlev",
    "interaktif": "etkileşimsel",
    "internet": "bilgisunar, genel ağ",
    "intiba": "izlenim",
    "intibak": "uyum, uyum sağlama",
    "intifa": "yararlanma",
    "intihar": "özkıyım, kendini öldürme",
    "intikal": "kavrama, geçme, göçme",
    "intikam": "öç",
    "intizam": "düzgünlük",
    "inziva": "yalnızlık",
    "inşallah": "tanrı dilerse",
    "ipnoz": "uyutum",
    "ipotek": "tutu",
    "iptal": "yürürlükten kaldırma",
    "iptidai": "ilkel",
    "irade": "istenç",
    "irat": "gelir",
    "irfan": "bilme, uzsezi",
    "ironi": "alaysama, alaysılama, gülünçleme",
    "irsaliye": "gönderme belgesi",
    "irsi": "kalıtsal",
    "irsiyet": "soyaçekim, kalıtım",
    "irtibat": "bağlantı",
    "irtica": "gericilik, gerilik",
    "irticalen": "doğaçlama, doğaçtan",
    "irtifa": "yükselti",
    "isabet ": "yerindelik",
    "isim": "ad",
    "isim": "ad",
    "iskonto": "indirim",
    "iskân": "yerleşme, yurtlandırma",
    "ispat": "tanıt, tanıtlama, kanıtlama",
    "israf": "tutumsuzluk, savurganlık",
    "istatistik": "sayılama, sayımsal",
    "istiare": "eğretileme",
    "istida": "dilekçe",
    "istidat": "yetenek",
    "istif": "düzgün yığın",
    "istifa": "çekilme",
    "istifade": "yararlanma",
    "istihdam": "işlendirme",
    "istihkak": "hakediş",
    "istihkâm": "sağlamlık",
    "istikamet": "yön",
    "istikbal": "gelecek",
    "istiklal": "bağımsızlık",
    "istikrar": "sürerge, düzen dengesi, değişmezlik",
    "istila": "yayılma",
    "istimlak": "kamulaştırma",
    "istinat": "dayanma",
    "istismar": "kötüye kullanma, sömürme",
    "istisna": "aykırılık, ayrınca",
    "istisnai": "ayrıksı, kuraldışı",
    "istişare": "danışma",
    "itaat": "boyun eğme",
    "itaatsiz": "sözdinlemez",
    "itfaiye": "söndürücü",
    "ithaf": "armağan ediş, sunu",
    "ithalat": "dışalım",
    "itham": "suçlama",
    "itibar": "saygınlık",
    "itikat": "inanç",
    "itilaf": "uyuşmazlık",
    "itina": "özen",
    "itiraz": "karşıdurma",
    "ittifak": "oybirliği, uyuşma, bağlaşma",
    "izafi": "bağıl, göreli, görece",
    "izaleişüyu": "ortaklığı bozma",
    "izan": "kavrayış, anlayış",
    "izbe": "sapa",
    "izdiham": "insan yığılması",
    "izdivaç": "evlenme",
    "izolasyon": "yalıtım",
    "izolebant": "yalıtım sargısı",
    "izzetinefis": "özsaygı, onur",
    "içtihat": "anlayış, görüş",
    "içtima": "toplanma, kavuşum",
    "iğfal": "kandırma, kandırılma",
    "işaret": "im, imlem, iz, belirti",
    "işgal": "oyalama, elegeçirme",
    "işkence": "kıyınç, yıldırı",
    "iştirak": "ortak olma",
    "jakoben": "tepeden inmeci",
    "jenerasyon": "soy, soydanlık, soykuşak",
    "jenerik": "tanıtımlık",
    "jeoloji": "yerbilim",
    "jest": "anlamlı davranış",
    "jet-ski": "su kızağı",
    "jogging": "koşu",
    "jurnal": "giziletim",
    "jübile": "kutlama töreni, onur töreni",
    "jüpon": "içetek",
    "jüri": "seçiciler kurulu",
    "kaale almak": "önem vermek, önemsemek",
    "kaale almamak": "sözünü etmemek",
    "kabil": "beklenir, olabilir, olası",
    "kabiliyet": "yetenek",
    "kabir": "gömüt",
    "kablelvuku": "olmadan önce",
    "kabotaj": "deniz işletmesi",
    "kabul etme": "onaylama",
    "kabza": "tutak",
    "kadar": "değin, dek, ölçüde",
    "kadastro": "yeryazım",
    "kadavra": "ölük",
    "kader": "alınyazısı, yazgı",
    "kadim": "eski, çoktanki",
    "kadir": "gücü yeter, değer, saygınlık",
    "kadirşinas": "değerbilir",
    "kafiye": "uyak",
    "kahraman": "yiğit",
    "kahır": "üzüntü, ezginlik",
    "kaide": "kural, taban",
    "kalbi": "içten",
    "kale": "kurgan",
    "kalibrasyon": "ölçümleme",
    "kalibre": "çapölçüsü",
    "kalifikasyon": "ustalık kazanma, niteliklilik",
    "kalifiye": "nitelikli",
    "kalorifer": "ısıveren, ısıtaç",
    "kalp": "yürek, gönül",
    "kambiyo": "değiştirim",
    "kamp": "dinlenek",
    "kampüs": "yerleşke",
    "kamuflaj": "gizleme",
    "kanaat": "kanı",
    "kanaatkâr": "yetingen",
    "kanalizasyon": "pis su yolu",
    "kani olmak": "inanmak",
    "kaparo": "önakça, güvenmelik",
    "kapasite": "sığa",
    "kapital": "anamal",
    "kapitülasyon": "ayrıcalık",
    "kapris": "özenç",
    "karakter": "ıra, özyapı",
    "karakteristik": "özgül, belirtici nitelik",
    "kargo": "yük, yüktaşır",
    "karikatür": "alaysı çizi, düşünçizi",
    "karikatürize": "gülünçleştirme",
    "karine": "ipucu",
    "kariyer": "uzmanlaşma",
    "karizma": "büyüleyim",
    "karizmatik": "büyüleyici",
    "kartvizit": "tanıtmalık",
    "kasko": "taşıt koruncası",
    "kasten": "isteyerek",
    "kasıt": "amaç, erek",
    "katil": "öldüren, öldürme",
    "katliam": "toplu öldürüm, kırım, kıyım",
    "katot": "eksi uç",
    "kavim": "budun, ulus",
    "kavis": "yay, eğmeç",
    "kaybetmek": "yitirmek",
    "kayyum": "temsilci, yönetici",
    "kayıp": "yitik",
    "keder": "üzünç",
    "kefalet": "yükümleme",
    "kefil": "yükümcü",
    "kehanet": "önbili",
    "kelime": "sözcük",
    "kemer": "belbağı",
    "kere": "kez",
    "ketum": "ağzısıkı",
    "keyfi": "isteğe bağlı",
    "keyif": "tat, sevini",
    "keza": "yine, öyle, bunun gibi",
    "keşişleme": "akçayel",
    "keşke": "ne olurdu",
    "keşmekeş": "karışıklık",
    "kibir": "büyüklenme",
    "kifayet": "yeterlik",
    "kinaye": "imleme, değinmece, dokundurma, kınama",
    "kinetik": "devinimsel",
    "kisve": "giyim, kılık, görüntüsü altında",
    "kitabe": "yazıt",
    "kitap": "okunca",
    "klan": "sop",
    "klas": "bölüt",
    "klavye": "tuşluk",
    "kliklemek": "tıklamak",
    "klima": "ısıdüzenleyici",
    "klişe": "kalıplaşmış",
    "kokteyl": "içkili toplantı",
    "kolaj": "kesyap",
    "kolektif": "işbirlikli, imeceli",
    "koloni": "sömürge",
    "kolonlama": "özdeşleme",
    "komandit": "karma sorumlu",
    "kombine": "birleşik",
    "komedi": "güldürü",
    "komik": "gülünç",
    "komisyon": "yüzdelik, yarkurul",
    "komite": "kurul",
    "kompleks": "karmaşık, altsanma",
    "komplikasyon": "istenmeyen durum",
    "komplike": "karmaşık, dolaşık",
    "kompliman": "okşam",
    "komplo": "gizdüzen",
    "kompozisyon": "düzenleyim",
    "kompozitör": "besteci",
    "komprador": "işbirlikçi",
    "kompütür": "bilgisayar",
    "komünikasyon": "iletişim",
    "kondisyon": "erk, tümdurum",
    "konfeksiyon": "giysi yapımı",
    "konfigürasyon": "yapılandırma",
    "konfirmasyon": "doğrulama, geçerleme",
    "konfor": "gönence",
    "kongre": "kurultay",
    "konjonktür": "topludurum",
    "konkordato": "batış anlaşması",
    "konsantrasyon": "dikkat toplaşımı",
    "konsensüs": "uzlaşım, anlaşım",
    "konsept": "kavram",
    "konser": "dinleti",
    "konserve": "saklanca",
    "konsolidasyon": "pekiştirme",
    "konsorsiyum": "uluslararası ortaklık",
    "konstrüksiyon": "yapım, yapı",
    "konsültasyon": "görüş alışverişi",
    "kontenjan": "önceden saptanmış pay oranı, saptanca",
    "konteynır": "kutuyük",
    "kontrast": "karşıtlık",
    "kontrat": "sözleşme",
    "kontrol": "denetim, denetleme, inceleme",
    "kontrolör": "denetçi",
    "konvansiyon": "anlaşma",
    "konşimento": "alındı belgesi",
    "koordinasyon": "eşgüdüm",
    "kopya": "eşlem, eşiz",
    "koridor": "geçenek",
    "korkunç": "yılınç",
    "korse": "sargaç",
    "kortej": "tören alayı",
    "kostüm": "giysi",
    "kota": "sınırsayı",
    "kozmonot": "uzayadamı",
    "kozmopolit": "evrendeş",
    "kozmos": "evren",
    "kramp": "kasınç, kasılma",
    "kravat": "boyunbağı",
    "kreasyon": "yaratı",
    "kredi": "ödenç, güven",
    "kredibilite": "güvenilirlik",
    "kriminoloji": "suçbilim",
    "kriter": "ölçüt",
    "kritik": "eleştiri, sorul",
    "kriz": "bunalım",
    "kroki": "taslak",
    "kromozom": "soyaktaran",
    "kronik": "süreğen",
    "kronoloji": "süredizin",
    "kros": "kır koşusu",
    "kulvar": "izleç, yürüyüş yolu",
    "kura": "ad çekme",
    "kurs": "özel öğrenim, alışım",
    "kursiyer": "alışman",
    "kurye": "özelulak",
    "kuvvet": "güç",
    "kâbus": "kArabasan",
    "kâfi": "yeterli",
    "kâh": "kimi",
    "kâhin": "bilici",
    "kâinat": "evren, acun",
    "kâr": "artınç",
    "kâtip": "yazman",
    "kâşif": "bulam",
    "kör": "görmez",
    "kötü talih": "karayazı",
    "küfür": "sövme, sövgü",
    "külliyetli": "çokça",
    "kültür": "ekin, özekin",
    "kümülatif": "katlanmış, yığışımlı",
    "küstah": "kendini bilmez",
    "kütüphane": "okuncalık",
    "kırtasiye": "yazı gereçleri",
    "kısas": "dişediş",
    "kıssa": "öğütlük, öğütçe",
    "kıstas": "ölçüt",
    "kıta": "anakara",
    "kıyafet": "giysi",
    "kıyaslama": "tasımlama, örnekseme",
    "kıymet hükmü": "değer yargısı",
    "kıymet": "değer",
    "laboratuvar": "deneylik",
    "laf": "söz",
    "lafügüzaf": "boşsözler",
    "lahit": "gömüt",
    "lakayt": "ilgisiz, kayıtsız, aldırmaz",
    "lakin": "ama, ancak, şu var ki",
    "lakırdı": "söz",
    "lal": "dilsiz",
    "lalettayin": "gelişigüzel, özensiz",
    "lanse etmek": "tanıtmak",
    "laptop": "dizüstü bilgisayar",
    "larenjit": "boğaz yangısı",
    "latife": "şaka",
    "laubali": "yılışık, senlibenli, kayıtsız",
    "lavabo": "elyunağı",
    "layık": "yakışan, yaraşık",
    "lazım": "gerek, gerekli",
    "lağvetme": "kaldırma, dağıtma, geçersiz kılma",
    "lebiderya": "deniz kıyısı",
    "legal": "yasal",
    "lehine": "yana, yararına",
    "levazım": "gereçler",
    "levha": "tanıtaç",
    "lezzet": "tat",
    "link": "bağlantı, ilişim",
    "lirik": "içsel, duyusal",
    "lisan": "dil",
    "lisans": "yetki belgesi",
    "liste": "dizelge",
    "literatür": "yazınca",
    "liyakat": "yararlık, yaraşırlık",
    "lizing": "kiralama",
    "lobi": "giriş, beklenek, etki küme’si",
    "lodos": "karayel",
    "logo": "simgeyazı, belirtke",
    "lojistik": "donanım",
    "lojman": "görevli konutu",
    "lokal": "yerel",
    "lokanta": "aşevi",
    "lokavt": "işkapatımı",
    "lâl": "bir tür süs taşı",
    "lügat": "sözlük",
    "lüzum": "gerek, gereksinim",
    "maalesef": "üzülerek söylüyorum, ne yazık ki",
    "macera": "serüven",
    "madde": "özdek",
    "maddi": "nesnel",
    "madem ki": "değil mi ki",
    "mafsal": "eklem, oynakyeri",
    "mahalli": "yerel",
    "mahcup": "sıkılgan, utangaç",
    "mahdut": "sınırlı, dar, birkaç",
    "mahfuz": "gizlenmiş, korunmuş",
    "mahiyet": "içyüz, nelik, nitelik",
    "mahkeme": "yargılık, yargıevi",
    "mahkûm": "yargın, yargılı",
    "mahluk": "yaratık",
    "mahpus": "tutuklanmış",
    "mahrem": "gizli, içrek, saklı",
    "mahrum": "yoksun",
    "mahsuben": "yerine sayarak",
    "mahsul": "ürün",
    "mahsur": "kuşatılmış",
    "mahsus": "özgü, bile bile",
    "mahvetme": "yok etme",
    "mahzun": "tasalı, kaygılı",
    "mahzur": "sakınca, çekince, engel",
    "maiyetinde": "yanında",
    "maişet": "geçim",
    "makam": "orun",
    "makara": "sarımlık",
    "makber": "gömüt",
    "makbul": "beğenilen, geçerli, uygun",
    "makbuz": "alındı",
    "maket": "küçültü",
    "maksat": "amaç, erek",
    "maksimum": "doruk, en üst, son sınır",
    "maktul": "öldürülen kişi",
    "makul": "anlayışlı, usa uygun",
    "makûs": "ters, uğursuz",
    "mal olan": "elde edilen",
    "mali": "akçalı",
    "malik": "iye",
    "maliyet": "eder",
    "malul": "sakat",
    "malum": "bilinen, belli",
    "malumat": "bilgi",
    "malzeme": "gereç",
    "mamafih": "bununla birlikte, yine de, böyle iken",
    "mamafih": "yine de, böyle iken",
    "mamul": "işlenmiş",
    "mamur": "bayındır",
    "mana": "anlam",
    "manevi": "öznel, tinsel, içsel, içlek",
    "maneviyat": "yürekgücü",
    "mani": "engel olan",
    "manidar": "anlamlı",
    "manifesto": "bildiri",
    "manipülasyon": "güdümleme, düzenci yönlendirme",
    "manivela": "kaldıraç",
    "mansiyon": "övgüdeğerlik ödülü, özendirme ödülü",
    "mantık": "sözge",
    "mantıklı": "usa yatkın, ussal",
    "manzara": "görünü, görünüş",
    "manzume": "uyaklı söz, sıra, dizi",
    "manşet": "üst başlık, kolluk",
    "maraton": "en uzun koşu",
    "maraz": "sayrılık",
    "marifet": "beceri",
    "marjinal": "sıradışı, uçta",
    "marka": "belik",
    "markaj": "tutma",
    "market": "satım yeri",
    "marketing": "pazarlama",
    "marmelat": "ezme",
    "maruz kalmak": "hedef olmak, karşılaşmak",
    "maruzat": "sunuş, diyecek",
    "masaj": "ovma",
    "mask": "yüzkalıbı",
    "maske": "örteç",
    "maskot": "uğurluk",
    "masraf": "gider",
    "mastar": "eylemlik",
    "masum": "suçsuz",
    "masör": "ovucu",
    "mat": "donuk",
    "matbaa": "basımevi",
    "matbu": "basılı",
    "matbuat": "basın",
    "matem": "yas",
    "matematik": "sayıbilim",
    "materyal": "gereç",
    "materyalist": "özdekçi",
    "matine": "gündüzlük",
    "matkap": "delgi",
    "mayo": "denizlik",
    "mayın": "patlatkı",
    "mazbata": "tutanak",
    "mazbut": "derli toplu",
    "mazeret": "engel, engellik",
    "mazhar": "erişmiş, erişen",
    "mazi": "geçmiş an",
    "mazlum": "uysal",
    "mazur": "özürlü",
    "mağdur": "haksızlığa uğramış, kıygın",
    "mağlup": "yenik",
    "mağrur": "kendini beğenmiş, kibirli",
    "meal": "anlam, kavram",
    "meblağ": "tutar",
    "mecal": "güç",
    "mecaz": "değişmece",
    "mecbur": "zorlanmış",
    "mecnun": "tutkun, çılgın",
    "mecra": "akak, su yolu",
    "meczup": "sapık",
    "med": "çekme",
    "medarı iftihar": "övünç nedeni, övünce",
    "meddah": "övücü",
    "medeni": "uygar",
    "medet": "yardım",
    "meditasyon": "derin düşünme, dalınç",
    "medya": "basın-yayın, ortam",
    "medyatik": "ünlü",
    "mefhum": "kavram",
    "mefruşat": "döşemelikler",
    "meftun": "vurgun, tutkun",
    "megaloman": "büyüklük delisi",
    "megapol": "devkent",
    "mehil": "süre tanıma, erteleme, önel",
    "mekanik": "devinimbilim",
    "mekanizma": "düzenek",
    "mektup": "beti, betik, yazınca",
    "mekân": "durulan oturulan yer, uzam, yerlek",
    "melankoli": "karakaygı",
    "melankolik": "içe kapanık",
    "melek": "gökçe",
    "meleke": "yeti, yatkınlık",
    "melez": "katışık",
    "melodi": "ezgi",
    "melül": "usanmış, bezgin",
    "memnu": "yasak",
    "memnun": "gönenmiş",
    "memorandum": "diplomatik nota",
    "memori": "bellek",
    "memur": "işyar",
    "men": "yasaklama, önleme",
    "mendirek": "dalgakıran",
    "menfaat": "çıkar",
    "menfez": "ağız",
    "menfi": "olumsuz",
    "menfur": "iğrenç",
    "mengene": "sıkmaç",
    "menkul": "taşınır",
    "mensup": "bağıntılı, ilintili",
    "menzil": "erim",
    "menşe": "kök, köken",
    "mera": "otlak",
    "meram": "istek, erek",
    "merasim": "tören",
    "merci": "başvurağı",
    "merhale": "aşama",
    "merhamet": "acıma",
    "meridyen": "boylam",
    "mersiye": "ağıt",
    "mesafe": "uzaklık",
    "mesai": "çalışma",
    "mesaj": "ileti, söylem, gönderi",
    "mesela": "örneğin, sözgelimi",
    "mesele": "sorun, konu",
    "mesire": "gezinti yeri",
    "mesken": "konut, oturulan yapı",
    "meskûn": "yerleşilmiş",
    "meslek": "geçimyolu, uğraşdalı",
    "meslektaş": "uğraştaş",
    "mesnet": "dayanak",
    "mest": "esrik",
    "mesul": "sorumlu",
    "met": "kabarma",
    "metafizik": "doğaötesi",
    "metamorfoz": "başkalaşma",
    "metanet": "dayanca",
    "metcezir": "gelgit",
    "meteor": "göktaşı",
    "methiye": "övgü, güzelleme",
    "metin": "yazı parçası, örü (ed), dayanıklı",
    "metodoloji": "yöntembilim",
    "metro": "yeraltı ulaşımı, alttaşıt",
    "mevcudiyet": "varlık, varoluş",
    "mevcut": "eldeki, var olan, bulunan",
    "mevduat": "Yatırım",
    "mevhum": "kavram, sanal",
    "mevki": "yer, konum",
    "mevkuf": "tutuk, tutuklu",
    "mevsim": "sürem",
    "mevta": "ölüler",
    "mevzu": "konu, bağlam",
    "mevzuat": "kurallar",
    "mevzubahis": "söz konusu",
    "mey": "içki",
    "mezar": "gömüt, sin",
    "mezat": "açık artırma",
    "mezbaha": "kesim yeri",
    "mezbele": "çöplük",
    "meziyet": "üstün nicelik, nitelik",
    "mezkûr": "adıgeçen",
    "mezra": "tarla",
    "mezun": "bitirmiş, yetkili",
    "meçhul": "bilinmedik, bilinmez",
    "meçhul": "bilinmeyen, belirsiz",
    "meğer": "oysa",
    "meşgale": "işgüç, uğraş",
    "meşgul": "dalgın, uğraşan",
    "meşguliyet": "uğraşı",
    "meşhur": "ünlü, angın",
    "meşru": "yasaya uygun",
    "meşrubat": "içecekler",
    "meşum": "uğursuz",
    "miat": "kullanım süresi",
    "mihenk": "denektaşı",
    "mihman": "konuk",
    "mihrak": "odak",
    "mikro": "minil",
    "mikrofon": "sesalır",
    "mikser": "çırpıcı",
    "milenyum": "binyıl",
    "militarizm": "orduculuk",
    "millet": "din, mezhep",
    "milletvekili": "saylav",
    "mimik": "kımıltı",
    "minimum": "en düşük, altsınır, en az",
    "minnet": "iyilik borcu",
    "miralay": "albay",
    "miras": "kalıt",
    "misafir": "konuk",
    "misak": "sözleşme, antlaşma",
    "misal": "örnek, sözgeliş",
    "mistik": "gizemli",
    "misyon": "görev, erek",
    "miting": "açık hava toplantısı",
    "mizah": "gülmece, alaysılama",
    "mizahi": "alaysı",
    "mizansen": "oyun düzeni",
    "mizaç": "özyapı",
    "moda": "izlenti",
    "model": "örüntü",
    "modem": "çevirge",
    "modern": "çağcıl",
    "modernizasyon": "yenileşme, çağcıllaşma",
    "modül": "bölüt",
    "modülasyon": "geçiş, değişme",
    "mola": "dinek, dinlenim",
    "molekül": "özdecik",
    "monarşi": "tekerklik",
    "monitör": "görüntülük, gösterici",
    "monogami": "tekeşlilik",
    "monolog": "tekli konuşma",
    "monoton": "tekdüze",
    "montaj": "kurma, kurgu",
    "moral": "yürek gücü, içgücü",
    "moratoryum": "borç erteleme",
    "morg": "ölüklük",
    "mortgeyç": "evedindirme",
    "mostralık": "göstermelik",
    "motif": "örge",
    "motiv": "güdü",
    "motivasyon": "isteklendirme",
    "muaccel": "ivedi",
    "muadil": "eşdeğer, denkteş",
    "muaf": "bağışık",
    "muafiyet": "bağışıklık",
    "mualla": "yüce",
    "muallak": "asılı, boşta",
    "muallim": "öğretmen, öğreten, eğiten",
    "muamelat": "işlemler",
    "muamele": "işlem, davranış",
    "muamma": "bilmece, gizlence",
    "muasır": "aynı yüzyılda, çağdaş",
    "muayene": "yoklama, sınama",
    "muazzam": "ulu",
    "muazzez": "saygıdeğer",
    "muaşeret": "görgü",
    "mucibince": "gereğince",
    "mucip sebep": "gerekçe",
    "mucit": "türetmen, bulan, buluşçu",
    "mucize": "tansık, olağandışı",
    "mudi": "yatırımcı",
    "muhabbet": "dostça söyleşme",
    "muhabere": "yazışma, haberleşme",
    "muhabir": "bildirmen",
    "muhacir": "göçmen",
    "muhafazakâr": "eskiye bağlı, tutucu",
    "muhafız": "kolcu",
    "muhakeme etme": "yargılama",
    "muhakeme": "uslamlama, usavurma",
    "muhalefet": "karşıtçılık",
    "muhalif": "karşıcıl",
    "muharebe": "savaşma",
    "muhasara": "kuşatma",
    "muhasebe": "saymanlık",
    "muhatap": "söz söylenen, karşımızdaki",
    "muhayyile": "düşgücü, imgelem",
    "muhbir": "eleveren",
    "muhit": "çevre, yöre",
    "muhlis": "katkısız",
    "muhtar": "özerk",
    "muhtasar": "kısaltılmış",
    "muhtaç olma": "gerekseme, gereksinme",
    "muhtelif": "çeşitli, türlü, ayrışık",
    "muhtemel": "olası",
    "muhterem": "saygıdeğer",
    "muhteris": "tutkulu",
    "muhteva": "içerik, kapsam",
    "muhteşem": "görkemli",
    "muhtıra": "andıç",
    "mukabele": "karşılık verme",
    "mukadderat": "alınyazısı, yazgı",
    "mukaddes": "kutsal",
    "mukallit": "öykünmeci",
    "mukavele": "sözleşme",
    "mukavemet": "karşı koyma, direniş, dayanırlık",
    "mukayese": "karşılaştırma, ölçüştürme, örnekseme",
    "mukayyet": "bağlı, işine önem veren",
    "muktedir": "becerebilen, gücü yeten",
    "multivizyon": "yansıtmalı gösterim",
    "munis": "sevimli, sıcakkanlı",
    "muntazam": "düzenli, düzgün",
    "murakıp": "denetçi",
    "muris": "kalıt bırakan",
    "musallat olma": "başına dolanma, sataşma",
    "musibet": "uğursuz, sıkıntı",
    "mustarip": "acı çeken, sıkıntı içinde olan",
    "mutaassıp": "bağnaz",
    "mutabakat": "uyum, uyuşma, oydaşma",
    "mutasyon": "değişinim",
    "mutat": "alışılmış",
    "muteber": "güvenilir, geçerli, saygın",
    "mutemet": "güvenilir kişi",
    "mutena": "özenilmiş, saygın",
    "mutlak": "tek, salt, yalnız, saltık",
    "mutlaka": "kesinlikle, ne olursa olsun",
    "mutluluk": "gönenç",
    "muvaffak": "başarılı",
    "muvazzaf": "ödevli, görevli",
    "muzaffer": "utkulu",
    "muğlak": "anlaşılmaz",
    "mönü": "yemek dizelgesi",
    "mübadele": "değiş tokuş",
    "mübah": "olurlu",
    "mübalağa": "abartı",
    "mübarek": "kutlu, uğurlu",
    "mübeccel": "yüce, ulu",
    "müberra": "aklanmış",
    "mücadele": "savaş, uğraş",
    "mücella": "parlak",
    "mücevher": "takı",
    "mücrim": "suçlu",
    "müdafaa": "savunma",
    "müdahale": "karışma, araya girme",
    "müdavim": "aralıksız katılan",
    "müddet": "süre",
    "müebbet": "sonsuz",
    "müessese": "işletme, kurum, kuruluş",
    "müessir": "etkili",
    "müeyyide": "yaptırım",
    "müfettiş": "denetmen",
    "müfit": "yararlı",
    "müflis": "batkın",
    "müfredat": "ayrıntılar",
    "mühim": "önemli",
    "mühimmat": "savaş gereçleri",
    "mühlet": "belirli süre",
    "müjde": "muştu",
    "mükellef": "yükümlü",
    "mükemmel": "eksiksiz, yetkin",
    "mükerrem": "saygın",
    "mükerrer": "yinelenmiş",
    "mükâfat": "ödül",
    "mülahaza": "düşünce, görüş",
    "mülakat": "görüşme",
    "mülazım": "teğmen",
    "mülk": "taşınmazmal",
    "mülkiyet": "iyelik",
    "mülteci": "sığınmacı",
    "mümkün mertebe": "olabildiğince",
    "mümkün": "olanaklı, olası",
    "mümtaz": "seçkin",
    "münafık": "ikiyüzlü",
    "münasebet": "ilişki, bağıntı, bağ",
    "münasip": "uygun, yaraşık",
    "münazara": "savlı tartışma",
    "münevver": "aydın",
    "münferit": "tekil, tek, kendi başına",
    "münhasır": "bir kişiye özgü",
    "münhasıran": "yalnızca",
    "müphem": "belirsiz, anlaşılmaz",
    "müptela": "tutulmuş, tutkun",
    "müracaat": "geri dönme, danışma, başvuru",
    "mürebbiye": "eğitici",
    "müreffeh": "baysal, gönençli",
    "mürekkep": "yazı boyası, bileşik",
    "mürit": "izdeş",
    "mürteci": "gerici",
    "mürüvvet": "iyilikseverlik",
    "mürşit": "yol gösterici",
    "müsabaka": "karşılaşma, yarışma",
    "müsait": "uygun, elverişli",
    "müsamaha": "görmezliğe gelme",
    "müsebbip": "neden olan",
    "müsekkin": "yatıştırıcı",
    "müselles": "üçgen",
    "müsemma": "davranışlarına aykırı adı olan, adlanmış",
    "müspet": "olumlu",
    "müsrif": "savurgan, tutumsuz",
    "müstahak": "yaraşık, kazanımlı, kazanılmış",
    "müstahdem": "görevli",
    "müstakbel": "gelecekteki",
    "müstakil": "bağımsız",
    "müstehcen": "açık saçık",
    "müstehzi": "alaycı",
    "müstemleke": "sömürge",
    "müsterih": "kaygısız, içi esen",
    "müstesna": "benzerlerinden üstün, ayrıcalı",
    "müstevli": "yayılan, ele geçiren",
    "müsvedde": "taslak",
    "mütalaa": "yorumlama, irdeleme",
    "mütareke": "silah bırakışması",
    "müteaddit": "birkaç, birçok, çok",
    "müteahhit": "yüklenici",
    "müteakiben": "ardı sıra",
    "müteessir": "etkilenen, üzülmüş",
    "mütehassis": "duygulanmış",
    "mütehassıs": "uzman",
    "mütemadi": "aralıksız, süren",
    "mütercim": "çevirmen",
    "mütereddit": "çekingen, ikircikli",
    "müteselsil": "ardı ardına",
    "mütevazı": "gösterişsiz, alçakgönüllü",
    "mütevekkil": "yazgıcıl",
    "mütevelli": "vakıf yöneticisi",
    "mütevellit": "den ileri gelmiş",
    "müteşebbis": "girişimci",
    "müteşebbis": "girişimci",
    "müteşekkir": "iyilik bilen",
    "müthiş": "ürküten, umulmayan",
    "müttefik": "bağlaşık, anlaşmış, oydaş",
    "müzakere": "görüşme",
    "müzayede": "artırma",
    "müzeyyen": "süslü",
    "müzmin": "süregen",
    "müşahede": "gözlem",
    "müşahit": "gözlemci, gözcü",
    "müşavir": "danışman",
    "müşerref olma": "onur duyma",
    "müşfik": "sevecen",
    "müşkül": "çetin, güç",
    "müşkülpesent": "güç beğenir",
    "müştak": "aşırı istekli",
    "müşteki": "sızlanan, yakınan",
    "müştemilat": "eklentiler",
    "müşterek": "birlikte, ortaklaşa",
    "müşteri": "alıcı",
    "mısra": "dizek, dize",
    "nabız": "atardamar vurgusu",
    "nadide": "görülmedik, ender",
    "nadim olma": "yerinme",
    "nadir": "az bulunur",
    "nafaka": "geçimlik",
    "nafile": "boşuna",
    "nahiye": "bucak",
    "nahoş": "beğenilmeyen",
    "nakavt": "oyundışı kalmak",
    "nakit": "akça",
    "nakkaş": "bezekçi",
    "nakletme": "taşıma, anlatma",
    "nakli": "söylenegelen",
    "nam": "san, ün",
    "namalum": "bilinmeyen",
    "namağlup": "yenilmemiş",
    "name": "betik",
    "namert": "alçak, korkak",
    "namzet": "aday",
    "namüsait": "elverişsiz",
    "nankör": "iyilik bilmez",
    "nara": "bağırış",
    "narenciye": "turunçgiller",
    "narin": "inceyapılı",
    "narkoz": "uyuşturma",
    "narsist": "özsever",
    "nasihat": "öğüt",
    "nasip": "düşem",
    "nasyonal": "ulusal",
    "natamam": "bitmemiş",
    "natürmort": "ölüdoğa",
    "navigatör": "yönlendirici",
    "nazar": "bakış, gözatma",
    "nazaran": "bakınca, göre, oranla",
    "nazari": "kuramsal, kurgul",
    "nazariye": "kuram",
    "nazarı dikkate almak": "önem vermek",
    "nazire": "benzek, benzetileme",
    "naçiz": "değersiz, önemsiz",
    "nağme": "ezgi, ses",
    "nebat": "bitki",
    "nebze": "bir parça, pek az",
    "necip": "soylu",
    "nedamet": "yerinme",
    "nefaset": "güzellik, değerlilik",
    "nefes": "soluk",
    "nefis": "çok güzel, özvarlık",
    "nefret": "iğrenme",
    "negatif": "olumsuz",
    "nekahet": "iyileşme",
    "nema": "artma, ürem",
    "neofobi": "yenilik korkusu",
    "neredeyse": "handiyse",
    "nesep": "soydanlık, soybağı",
    "nesil": "kuşak, döl, soy",
    "nesir": "düzyazı",
    "netice": "sonuç",
    "netvörk": "bilişimağı",
    "nevroloji": "sinirbilim",
    "nevroz": "sinirce",
    "nezaket": "incelik",
    "nezaret etme": "bakma, gözetme",
    "nezarete alma": "gözaltı",
    "neşriyat": "yayın",
    "nida": "ünlem, haykırı",
    "nifak": "ayırga, ayrım",
    "nigâr": "güzel, sevgili",
    "nihai": "son",
    "nihayet": "son, sonunda",
    "nimet": "ergi",
    "nispet": "oran",
    "nispeten": "başkalarına bakınca",
    "nispi": "görece",
    "nitekim": "nasıl ki, sonuçta, gerçekten",
    "niyet": "erek",
    "nizam": "düzen, yol",
    "nizamname": "tüzük",
    "nişan almak": "gezlemek",
    "nişan": "im, iz, belirti",
    "nişangâh": "bakıncak",
    "nodül": "yumrucuk",
    "nofrost": "karlanmaz",
    "noksan": "eksik",
    "nokta": "durgu, benek",
    "norm": "izge, ölçü, kural, ilke",
    "normal": "olağan",
    "nostalji": "dünözlem, özlenç",
    "nostop": "durmasız",
    "nosyon": "kavrayış",
    "not": "saptam",
    "numara": "sırasayı",
    "numune": "örnek",
    "nutuk": "söylev",
    "nâzım": "düzenleyen",
    "nöroloji": "sinirbilim",
    "nötr": "yansız",
    "nötralizasyon": "etkisizleştirmek",
    "nü": "çıplak",
    "nüans": "ince ayrım, ayırtı, ayrımcık",
    "nüfus": "yaşayanlar, insanlar",
    "nüfuz": "söz geçerlik, saygınlık",
    "nüksetme": "depreşme",
    "nükte": "ince anlamlı",
    "nüsha": "eşiz, eşyazı",
    "nüve": "çekirdek",
    "o hâlde": "öyleyse",
    "obezite": "sağlıksız şişmanlık",
    "obje": "nesne",
    "objektif": "nesnel",
    "obligasyon": "yükümlülük",
    "obsesif": "önyargılı, takıntılı",
    "ofis": "işyeri",
    "ofsayt": "açığa düşme",
    "ofset": "düzbaskı",
    "okeyleme": "oldulama, onaylama",
    "ombudsman": "kamu denetçisi",
    "onlayn": "çevrimiçi",
    "onore": "onursal",
    "operasyon": "işlemce",
    "oportünist": "çıkarcı",
    "opsiyon": "seçme yetkisi",
    "optimizm": "iyimserlik",
    "optimum": "en uygun",
    "ordövr": "önyemek",
    "organ": "örgen",
    "organize etmek": "düzenlemek",
    "orijin": "köken, başlangıç, kök",
    "orijinal": "özgün",
    "oryantal": "doğuya ilişkin",
    "oryantasyon": "alıştırma, uyum",
    "otantik": "gerçek, özgün, yerel",
    "otel": "kalıncak",
    "otizm": "içe kapanış",
    "otobiyografi": "özyaşam öyküsü",
    "otokritik": "özeleştiri",
    "otomasyon": "kendiişlerlik",
    "otomatik": "kendiişler, özdevinim",
    "otonom": "özerk",
    "otopsi": "gözle görü, ölüaçımı",
    "otorite": "yetke",
    "otoriter": "sözdinletir",
    "otosansür": "özdenetim",
    "pakt": "antlaşma, bağıt",
    "paleontoloji": "eski varlıkbilim, taşılbilim",
    "palyatif": "geçici, anlık",
    "pandomim": "sessiz oyun",
    "panel": "açık oturum",
    "panik": "ürkü",
    "pankart": "duyurumluk",
    "pano": "duyuru tahtası",
    "panorama": "genel görünüm",
    "pansiyon": "barıncak",
    "para": "akça",
    "paradigma": "değerler dizisi, örneksem",
    "paradoks": "aykırı düşünce, karşıtlam, çelişki",
    "paraf": "imce",
    "paragraf": "bölümce, bölüntü",
    "paralel": "koşut, enlem",
    "parametre": "değiştirgen, değişken",
    "paranoya": "kuşkucu",
    "parantez": "ayraç",
    "paratoner": "yıldırımsavar",
    "paravan": "bölmelik, gerelti",
    "parazit": "asalak",
    "pardon": "bağışlayın",
    "parfüm": "güzel koku",
    "parite": "değer eşitliği",
    "parkur": "koşmalık, koşuyolu",
    "parlamento": "kamutay",
    "parodi": "gülünçleme",
    "parola": "açkı sözcük, kipsöz",
    "parsel": "bölgü",
    "partner": "eş, ortak",
    "parttaym": "yarıgün",
    "pasaport": "geçişlik",
    "pasif": "edilgen, eylemsiz",
    "paso": "yolkimliği",
    "pastoral": "kırsal",
    "pastörize": "arınmış",
    "paten": "kaymalık",
    "patent": "buluş belgesi",
    "patika": "yolak, izlek",
    "patoloji": "hastalıklar bilimi",
    "patron": "işveren",
    "payidar": "kalımlı",
    "payidar": "kalımlı",
    "pedagoji": "eğitimbilimi, eğitbilim",
    "pekâlâ": "pekiyi, peki",
    "pencere": "bakanak",
    "perakende": "tekten, azar azar",
    "performans": "başarımgücü, beceri, kazanma isteği, gösteri, oyun",
    "pergel": "yayçizer",
    "periyodik": "dönemli, dönüşümlü",
    "periyot": "sıralama, döngü",
    "perişan olmak": "sınmak",
    "perküsyon": "vurmalı (çalgı)",
    "personel": "görevliler",
    "perspektif": "görünge, derinlik",
    "perva": "çekinme",
    "pervane": "dönencek",
    "pervasızca": "çekinmeksizin",
    "pesimist": "karamsar, kötümser",
    "pey": "önakça",
    "peygamber": "tanrı elçisi, yalvaç",
    "peyzaj": "kır görüntüsü, görünü",
    "peşin hüküm": "önyargı, takınç, önsayıltı",
    "peşinat": "önödeme",
    "pilot": "uçman",
    "pist": "yarışlık",
    "piston": "itenek",
    "piyes": "oyun",
    "pişmanlık": "yerinme, yazıklanma, hayıflanma",
    "plaj": "kumsal",
    "plaka": "tanıtaç",
    "plaket": "onurluk, anımlık",
    "plan": "izlek, tasarı",
    "plasiye": "gezgin satıcı",
    "plasman": "yatırım",
    "pleybek": "söylemseme",
    "podyum": "seki, görümlük",
    "polemik": "söz (yazı) dalaşı, tartışı",
    "polifoni": "çokseslilik",
    "poligami": "çokeşlilik",
    "poligon": "atış alanı, çokgen",
    "poliklinik": "toplubakılık",
    "polinom": "çok terimli",
    "polis": "kolluk",
    "polisiye": "güvenlikle ilgili",
    "politika": "ülke yönetimi, yönelti",
    "popülasyon": "insan sayısı, varlık",
    "popüler": "sevilen, tanınan",
    "popülist": "yardakçı, yaranmacı",
    "portatif": "taşınabilir",
    "portföy": "akçalık, belgitlik",
    "portmanto": "askılık",
    "portre": "betimce",
    "potansiyel": "gizilgüç",
    "potin": "boğazlı ayakkabı",
    "potpuri": "karmaca",
    "poyraz": "kuzey yeli",
    "poz": "duruş",
    "pozisyon": "konum, durum",
    "pozitif": "olumlu, artı",
    "poşet": "torba",
    "pragmatik": "yararcı",
    "pratik": "kılgısal, uygulamalı",
    "pratisyen": "uzman olmayan, sağıtman",
    "praymtaym": "izlencelik",
    "prefabrik": "kurma, hazıryapım ev",
    "prensip": "ilke",
    "pres": "sıkacak, baskı",
    "prese": "sıkıştırılmış",
    "prestij": "saygınlık",
    "prezantabl": "sunulmaya değer",
    "prezante": "tanıştırma, sunma",
    "prezervatif": "koruyucu",
    "prim": "iş ödülü",
    "printir": "yazıcı",
    "priz": "girgilik",
    "problem": "sorun",
    "prodüksiyon": "yapım",
    "prodüktivite": "verimlilik",
    "prodüktör": "yapımcı",
    "profesyonel": "uğraşman",
    "profil": "yan görünüm",
    "program": "tasımlama, izlence",
    "proje": "öntasarı, tasarı",
    "projeksiyon": "yansıtım",
    "projektör": "ışıldak",
    "proleter": "emekçi",
    "prolog": "önsöz, öndeyiş",
    "promosyon": "özendirme",
    "propaganda": "tanıtma, yayma",
    "propagandist": "tanıtman",
    "prosedür": "yöntem, yol, izlek",
    "proses": "süreç",
    "prosesör": "işlemci",
    "prospektüs": "tanıtmalık",
    "protez": "takma",
    "protokol": "tören düzen, sözleşme",
    "prototip": "ilk örnek",
    "prova": "deneme, sınama",
    "provizyon": "karşılık sorma, karşılık denetimi",
    "provoke etmek": "kışkırtmak",
    "prömiyer": "ilk oyun, ilk gösteri",
    "psikanaliz": "tinsel çözümleme",
    "psikolog": "tinbilimci",
    "psikoloji": "ruhbilim, tinbilim",
    "put": "tapıncak",
    "rabıta": "bağ, ilişki",
    "radde": "kerte, aşama",
    "radikal": "kökten, köktenci",
    "radyasyon": "ışıma, ışınım",
    "radyatör": "ısıyayar, ısısalar",
    "radyoaktif": "ışınetki",
    "radyolink": "telsiz bağlantı",
    "radyoloji": "ışınbilim",
    "radyometre": "ışınölçer",
    "radyoterapi": "ışınlı sağaltım",
    "rafinaj": "arıtım",
    "rafine": "arıtılmış",
    "rafting": "sal yarışı",
    "rahata kavuşma": "gönenme, dirlik içinde olma",
    "rahim": "döl yatağı",
    "rahîm": "esirgeyen",
    "raket": "vuraç",
    "rakip": "karşı olan",
    "rakip": "karşı olan, yarışan",
    "ramak": "az bir şey",
    "randıman": "verim",
    "rant": "getirim, emeksiz gelir",
    "rantabilite": "verimlilik",
    "rapor": "incelem, yazanak",
    "raportör": "incelemeci",
    "rapt": "iliştirme",
    "rasat": "gözlem",
    "rasathane": "gözlemevi",
    "rasyonalist": "usçu",
    "rasyonel": "usa dayanan, ussal",
    "ray": "kayga",
    "rayiç": "geçerdeğer",
    "razı olmak": "uygun bulmak",
    "rağbet": "ilgi, değer verme",
    "rağmen": "karşın, yine de",
    "reaksiyon": "tepki, tepkime",
    "realist": "gerçekçi",
    "realite": "gerçeklik",
    "realizm": "gerçekçilik",
    "redaksiyon": "yazımlama, yazıdüzen, yayımdüzen",
    "reddi hâkim": "yargıcın duruşmadan çekilmesini istemek",
    "reddiye": "savunum",
    "redüksiyon": "indirgeme",
    "reel": "gerçek",
    "reenkarnasyon": "tin göçü",
    "reeskont": "ikinci kırdırma",
    "refah": "gönenç, bolluk, dirlik",
    "refakat": "eşlik etme, yoldaşlık",
    "referandum": "halkoylaması, tümdanış",
    "referans": "başvuru, kaynak, yararlılık belgesi",
    "refleks": "tepke",
    "reflektör": "yansıtıcı",
    "reform": "dönüşüm, düzeltme",
    "refüj": "orta kaldırım",
    "refüze": "geri çevirme",
    "regülatör": "düzenleyici, düzenleç",
    "rehabilitasyon": "iyileştirme",
    "rehavet": "gevşeklik, tembellik",
    "rehber": "yol gösterici, yol gösteren",
    "rehin": "tutu",
    "rejim": "yönetim",
    "rejisör": "yönetmen",
    "rekabet": "yarışma, çekişme",
    "reklam": "tanıtı, özendirim",
    "rekolte": "yıllık ürün",
    "rekor": "en üstün aşama, üsterişim",
    "rekortmen": "erişmen",
    "rencide olma": "incinme",
    "rengârenk": "alacalı",
    "rençper": "tarımcı",
    "repertuar": "sunumluk",
    "repertuvar": "sunumluk",
    "reprezant": "tanıtımcı",
    "reprodüksiyon": "özdeş baskı, eşiz baskı",
    "resen": "kendi başına, kendiliğinden, doğrudan doğruya",
    "resepsiyon": "başvuru yeri, törençağrı",
    "resesif": "çekinik",
    "resim": "boyam, bezek",
    "resmen": "bile bile, devlet adına",
    "resmi geçit": "geçit töreni",
    "restoran": "aşevi",
    "restorasyon": "onarım",
    "ret": "geri çevirme, yadsıma, olmazlama",
    "reva": "uygun, yakışır",
    "revanş": "karşılık oyun",
    "revaç": "herkesçe aranılma, geçerlik",
    "revir": "bakım odası",
    "revize": "yenileme, düzeltme",
    "rey": "oy, görüş",
    "reyting": "izlenme oranı",
    "rezervasyon": "yer ayırtımı",
    "rezervuar": "biriktirici",
    "rezidans": "konut",
    "rezistans": "direnç",
    "rezonans": "eşsalınım, seselim, tınlaşım",
    "reşit": "ergin",
    "ribaunt": "dönen top",
    "rica": "dileme",
    "risk / riziko": "zarara uğrama tehlikesi, dokuncak",
    "ritim": "dizem",
    "ritmik": "düzenli, dizemli",
    "ritüel": "ayinsel, törensel",
    "rivayet": "duyultu, söylenti",
    "riyakâr": "ikiyüzlü",
    "rodaj": "alıştırma",
    "roman": "uzun öykü",
    "romantik": "duygusal, düşsel",
    "rotasyon": "döngü, düzenli değişim, dönüşümlü görev",
    "rotatif": "döner-basar",
    "ruh": "tin, öz",
    "ruhsal": "tinsel, içsel",
    "rumuz": "simge",
    "rut": "dizin",
    "rutin": "alışılagelmiş, sıradan, yapılagelen",
    "râhim": "acıyan",
    "râkım": "yazan, denizden yükseklik",
    "rölanti": "yavaşlatılmış",
    "rölyef": "kabartma",
    "römork": "takıt",
    "römorkör": "takıtçeker",
    "röportaj": "söyleşi, görüşme",
    "rötar": "gecikme",
    "rötuş": "düzeltme",
    "rövanş": "ikinci karşılaşma, karşılık oyun",
    "rücu": "geri dönme",
    "rüya": "düş",
    "rüzgâr": "eser, yel",
    "rüşt": "ergenlik",
    "saadet": "mut, mutluluk",
    "sabit": "değişmez, durağan",
    "sabote / sabotaj": "kundaklama, baltalama",
    "sabık": "eski, önceki, geçen",
    "sabıka": "geçmiş suç",
    "sabır": "dayanma gücü, dayanç",
    "sade": "katışıksız, yalın, düz",
    "sadece": "yalnız, yalnızca",
    "sadet": "erek, asıl konu",
    "saf": "sıra, dizi, katışıksız",
    "safha": "evre",
    "sahip": "iye, ıs",
    "sahte": "düzmece",
    "sakil": "çirkin",
    "sakin": "susuk, duruk, dingin",
    "salahiyet": "yetki",
    "samimi": "içten, gönülden, içlidışlı, senlibenli",
    "sanayi": "yapın, işleyim",
    "sanki": "sözümona",
    "sansasyon": "ilgi yaratma, çarpıcılık",
    "sansür": "sıkıdenetim",
    "sarih": "açık, apaçık",
    "sathi": "yüzeysel, üstünkörü",
    "satıh": "yüzey",
    "satır": "dizek",
    "sauna": "buhar banyosu",
    "sav": "tez",
    "saye": "gölge, koruma",
    "sayesinde": "yüzünden, katkılarıyla",
    "seans": "oturum",
    "sebat": "direnim, direnme",
    "sebep": "neden",
    "seciye": "ıra, özyapı",
    "seda": "ses, yankı",
    "sedimantasyon": "tortu çökmesi",
    "sefalet": "yoksulluk",
    "sefaret": "elçilik",
    "sefer": "yolculuk, savaş",
    "sefir": "elçi",
    "sehven": "yanlışlıkla, yanılarak",
    "sekte": "durma, durgu, aksama",
    "sektör": "kesim, bölüm",
    "selamlama": "esenleme",
    "selef": "öncül, öncel",
    "self-servis": "kendinal",
    "sema": "gökyüzü",
    "semavi": "göksel",
    "sembol": "simge",
    "sembolik": "simgesel",
    "semere": "sonuç alma",
    "semere": "verim, yarar, kâr, sonuç",
    "semih": "eli açık",
    "seminer": "topluçalışım",
    "sempatik": "sevimli, kanı sıcak",
    "sempatizan": "duygudaş",
    "sempozyum": "bilgi şöleni, bilimtay",
    "semptom": "bulgu",
    "sendika": "emekçi birliği",
    "sendrom": "belirti, belirgi",
    "sene": "yıl",
    "senet": "belge, belgit",
    "seneyi devriye": "yıldönümü",
    "senkron": "eşsüre, eşsürem",
    "senkronik": "eşsürelik",
    "senkronizasyon": "eşleme",
    "sensör": "duyar",
    "sentetik": "bireşimli, yapay",
    "sentez": "bileşim",
    "ser": "baş, başkan",
    "serap": "ılgım, yalgın",
    "serbest": "bağımsız, özgür, engelsiz",
    "serdar": "başkomutan",
    "seremoni": "tören",
    "sergüzeşt": "serüven",
    "serhat": "sınırboyu",
    "seri": "hızlı, ivedi",
    "serigraf": "ipek baskıcı",
    "serkeş": "dikbaşlı",
    "sermaye": "anaakça",
    "sersem": "sangı",
    "serseri": "başıboş, kopuk",
    "sertifika": "bitirme belgesi",
    "server": "başkan",
    "servet": "varlık",
    "serzeniş": "başa kakma",
    "serî": "sıra, sıralı",
    "set": "tümsek, engel, büget",
    "seviye": "düzey",
    "sevk etme": "gönderme, yollama",
    "seyahat": "gezi, yolculuk",
    "seyir": "bakış, izleme, gezinme",
    "seyran": "gezme, gezinme",
    "seyrüsefer": "gidiş geliş",
    "seyyah": "gezgin",
    "seyyal": "akışkan, akıcı",
    "seyyanen": "eşit olarak, eşitçe",
    "seyyar": "gezici",
    "sezon": "sürem, dönemce",
    "sicil": "kayıt kütüğü",
    "sigorta": "korunç, koruncalık, güvenmelik",
    "sihir": "büyü",
    "silsile": "soysop",
    "siluet": "karaltı",
    "simetri": "bakışım",
    "simetrik": "bakışık, bakışımlı",
    "simsar": "aracı",
    "simülasyon": "benzetim",
    "simülatör": "benzetimlik, öykünmelik",
    "simültane": "ânında çeviri",
    "sinerji": "ortakenerji, görevdeşlik",
    "sipariş": "ısmarlama",
    "siper": "korunak",
    "sirayet": "bulaşma, yayılma, geçme",
    "sirkülasyon": "dolanım, dolaşım",
    "sirküler": "genelge, duyurum",
    "sismik": "depremsel",
    "sismograf": "depremölçer",
    "sismoloji": "deprembilim",
    "sistem": "dizge, yöntem, yoldam",
    "sistematik": "dizgeli",
    "site": "özerkkent",
    "sitem": "iğneleme",
    "sitilize": "biçimleme",
    "sivil": "yurttaşlara ilişkin",
    "siyaset": "ülke yönetimi",
    "skala": "gösterge çizelgesi",
    "skandal": "utanca",
    "skenır": "tarayıcı",
    "skeç": "oyunca",
    "ski": "kayak",
    "skor": "sonuç, durum",
    "skorbord": "sayı tahtası",
    "slayt": "yansı",
    "slogan": "savsöz, özlüsöz",
    "smaç": "küt inme",
    "snekbar": "atıştırma yeri",
    "softver": "yazılım",
    "sohbet": "konuşu, söyleşi",
    "sokak": "yerleşim aralığı",
    "solaryum": "güneş odası",
    "solüsyon": "çözelti",
    "sonbahar": "sonyaz, güz",
    "sonda": "burgu",
    "sondaj": "burgu vurma",
    "sosyal": "toplumsal",
    "sosyalist": "toplumcu",
    "sosyalizasyon": "toplumsallaştırma",
    "sosyete": "yüksek tabaka",
    "sosyoloji": "toplumbilim",
    "spekülasyon": "vurgunculuk, kurgu",
    "spekülatif": "tartışılır",
    "spekülatör": "vurguncu, çıkarcı",
    "spesifik": "özellikli, özgül",
    "spesiyal": "kendine özgü, özel",
    "spiker": "konuşman",
    "spiral": "sarmal",
    "sponsor": "akçalayan, katkıcı, parasal destekçi",
    "spontane": "kendiliğinden oluşan",
    "spot": "ışıntı, önödemeli",
    "sprey": "püskürtücü",
    "stabil": "yerleşik, oturmuş",
    "staj": "yetişim",
    "stajyer": "yetişmen",
    "stand": "bölme",
    "standardize": "ölçünleme",
    "standart": "tekörnek, tekbiçim, ölçünlü",
    "stant": "sergilik",
    "star": "yıldız",
    "start almak": "başlamak",
    "start": "çıkış, başlangıç",
    "stat": "yarışma alanı",
    "statik": "durağan",
    "statü": "tüzük, kural, konum",
    "statüko": "sürerdurum",
    "stendbay": "destek, yedek",
    "stenografi": "imyazı",
    "step": "adım, bozkır",
    "stepne": "yedek teker",
    "steril": "arınık",
    "stikı / stikır": "yapışkı",
    "stil": "biçim, yoldam",
    "stilist": "biçimci, giyimçizer",
    "stok": "yığım",
    "stop": "dur",
    "stopaj": "önkesinti",
    "stoper": "durdurucu",
    "strateji": "yolgüdüm, yordam",
    "stres": "gerginlik",
    "sual": "soru",
    "suare": "gece gösterisi",
    "sufle": "fısıldama",
    "suiistimal": "kötüye kullanım",
    "suikast": "öldürme girişimi",
    "sukut": "düşme",
    "sukutuhayal": "düş kırıklığı",
    "sulh": "barış, uzlaşma",
    "sulta": "yetke",
    "suni": "yapay, yapmacık",
    "supap": "kapakçık, kapaç",
    "supervayzır": "denetleyici",
    "suret": "dış görünüm, eşiz",
    "sutyen": "göğüsbağı",
    "sömestr": "yarıyıl",
    "sörvır": "bakım birimi",
    "sübjektif": "öznel, kişisel, taraflı",
    "sübvansiyon": "destekakça",
    "sükûn": "dinginlik",
    "sükût": "susma, susku",
    "sülale": "soysop",
    "sürpriz": "şaşırtı",
    "sürrealist": "gerçeküstücü",
    "süspansiyon": "yaylanma",
    "süvari": "binici, atlı",
    "sıfat": "önad, nitelik, niteç, nitem",
    "sıhhat": "sağlık, esenlik, doğruluk",
    "sıklet": "ağırlık, yük, sıkıntı",
    "sıla": "kavuşma",
    "sınai": "işleyimsel",
    "sınıf": "bölüm, bölüt, kat, katman, öğretilik",
    "sır": "giz, gizem",
    "sırdaş": "gizdeş",
    "sırf": "salt, yalnız, ancak",
    "taahhüt": "üstlenme, antlaşma",
    "taahhütlü": "bağıtlı",
    "taammüden": "tasarlayıp",
    "taarruz": "saldırı",
    "taassup": "bağnazlık",
    "taba rengi": "tütünsü",
    "tabaka": "kat, katman",
    "tabedilmiş": "basılmış",
    "tabela": "tanıtaç",
    "tabi olmak": "boyun eğmek, bağlanmak, uymak",
    "tabiat": "doğa",
    "tabiatıyla": "doğal olarak",
    "tabii": "doğal, olağan",
    "tabip": "sağın",
    "tabir": "deyim, terim",
    "tabiri caizse": "deyim yerindeyse",
    "tabla": "sergi",
    "tabldot": "seçmesiz yemek",
    "tablo": "çizelge",
    "tabu": "yasak",
    "tacir": "alımsatımcı, tecimen",
    "tadilat": "değişiklik",
    "tafsilat": "ayrıntı, açıklama",
    "tahakkuk": "gerçekleşme",
    "tahakküm": "baskı",
    "tahammül": "dayanma",
    "tahammül": "katlanma, yüklenme",
    "tahayyül": "düşgörü, imgelem",
    "tahdit": "sınırlama, kısma",
    "tahkik": "araştırma",
    "tahkikat": "soruşturma",
    "tahkim": "pekiştirme, sağlamlaştırma",
    "tahkir": "küçük görme",
    "tahlil": "çözümleme, inceleme",
    "tahliye": "boşaltma, salıverme",
    "tahmin": "öngörü, kestirim",
    "tahrif": "bozma, değiştirme",
    "tahrik": "kışkırtı, devindirme",
    "tahrip": "yıkıp bozma",
    "tahrir": "yazma, yazı",
    "tahsil": "öğrenim, elde etme, toplama",
    "tahsis": "özgüleme",
    "tahsisat": "ödenek",
    "takdim": "sunu",
    "takdir": "beğenme, değerleme, yazgı, öyle sanma",
    "takdiri ilahi": "yazgı",
    "takdis": "kutsallaştırma, kutsama",
    "takibat": "kovuşturma",
    "takip": "izleme",
    "takip": "izleme",
    "takiye": "yalansama",
    "taklit": "öykünme, özenti",
    "taksit": "bölüt",
    "taktik": "yönlem",
    "taktir": "damıtma",
    "takvim": "günbilgisi",
    "takviye": "berkitme, pekiştirme",
    "talep": "istek",
    "talep": "istem",
    "tali": "ikincil",
    "talim": "alıştırı, öğretilme, öğretme",
    "talimat": "buyruk",
    "talip": "istekli, isteyen",
    "talk-show": "ayaküstü söyleşi",
    "taltif": "ödüllendirme",
    "tamah": "açgözlülük",
    "tamim": "genelge",
    "tamir": "onarım",
    "tandans": "eğilim, yönseme",
    "tansiyon": "kan basıncı, gerilim",
    "tanzim": "düzenleme",
    "taraftar": "yandaş",
    "tarif": "tanım",
    "tarz": "yoldam, biçim",
    "tasarruf": "tutum, artırım, kullanım",
    "tasarrufu teşvik": "tutumu özendirme",
    "tasavvur": "tasarlama, tasarım, düşkurma",
    "tasdik": "onaylama",
    "tasfiye": "temizleme",
    "tasnif": "sınıflama, ayrılama, bölümleme",
    "tasvip": "uygun bulma, onama",
    "tasvir": "betimleme",
    "tatbik": "uygulama",
    "tatil": "ara verme, dinlence",
    "tatmin": "doyum",
    "tatminkâr": "doyurucu",
    "tatminsiz": "doyumsuz",
    "taviz": "ödün",
    "tavsiye": "öğüt, salık verme",
    "tayyare": "uçak",
    "taziye": "başsağlığı",
    "tazminat": "ödence",
    "tazyik": "basınç",
    "taç atışı": "yan atış",
    "teamül": "olagelen işlem, alışkı, yapılagelmiş",
    "teatral": "tiyatro oyununa benzer",
    "tebaa": "uyruk",
    "tebdil": "başkalaştırma",
    "teberru": "bağış",
    "tebligat": "bildirim",
    "tecil": "erteleme",
    "tecrit": "soyutlama",
    "tecrübe": "deneyim",
    "tedarik": "edinme, edinim",
    "tedavi": "sağaltım",
    "tedavül": "geçerlik, sürüm",
    "tedbir": "önlem",
    "tediye": "ödeme, ödenilme",
    "tedricen": "giderek",
    "teessüf": "acıma",
    "teessür": "içlenme",
    "tefekkür": "akıl yorma",
    "teferruat": "ayrıntı",
    "tefrik": "ayrı tutma, ayırtsama",
    "tefrika": "sürmece",
    "tefsir": "yorum",
    "tehcir": "göç ettirme",
    "tehdit": "gözdağı",
    "tehir": "geciktirme",
    "tekabül": "eşiti, yerini tutma, uygu",
    "tekerrür": "yinelenme",
    "teklif": "öneri",
    "teknoloji": "uygulayımbilim",
    "tekrar": "gene, yine, yineleme",
    "teksir": "çoğaltma",
    "tekzip": "yalanlama",
    "tekâmül": "evrim, gelişme, olgunlaşma",
    "telaffuz": "sesletim, söyleyiş",
    "telafi": "yerini doldurma, giderme",
    "telakki": "kabullenme",
    "telef": "yok olma, yok etme, yitme",
    "telefon": "sesiletir",
    "telepati": "uzaduyum",
    "telif": "toplayıp yazma, uzlaştırma",
    "telkin": "aşılama",
    "tema": "anaduygu, izlem, izlek",
    "temas": "ilişme, değinim",
    "temayül": "eğilim",
    "tembel": "üşengeç",
    "tembellik etmek": "yüksünmek",
    "tembih": "uyarı",
    "temenni": "dilek",
    "temettü": "kâr etme",
    "teminat": "güvence, inanca",
    "temsil": "gösterim, örnek, benzetme, andırış",
    "temyiz": "iyiyi kötüden ayırt etme",
    "tenakuz": "karşıtlık, çelişme, çelişki",
    "teneffüs": "solunum, soluklanma",
    "tenezzül etme": "aşağılaşma",
    "tenkit": "eleştiri",
    "tenzih": "ayrı tutma, ayrılama",
    "tenzilat": "indirim",
    "teorem": "önerme",
    "teori": "kuram",
    "tercih": "üstün tutma, yeğleme",
    "tercüman": "dilmaç",
    "tereddüt": "ikircik, duraksama",
    "tereke": "bırakıt",
    "terfi": "yükseltilme",
    "termometre": "sıcaklıkölçer",
    "termostat": "ısıdenetir",
    "tertip": "düzen",
    "terör": "yıldırı",
    "terörist": "yılgıcı",
    "tesadüf": "rastlantı",
    "tescil": "kayıt altına alma",
    "teselli": "avundurma, avuntu",
    "tesettür": "gizlenme, kapanma",
    "tesir": "etkime, etki",
    "tesisat": "donanım, döşem",
    "teskin": "yatıştırma",
    "tespit": "saptama",
    "test": "deneme, sınama",
    "tevatür": "söylenti",
    "tevazu": "alçakgönüllülük",
    "teveccüh": "ilgi gösterme, sevgi",
    "tevekkül": "yazgıya boyun eğme",
    "tevessül": "neden olma, başvurma",
    "tevkif": "alıkoyma",
    "tevzi": "dağıtılma, dağıtım",
    "teyakkuz": "uyanıklık",
    "teyit": "doğrulama, gerçekleme",
    "teyp": "sesalıcı",
    "tez": "savunca, savunu, sav",
    "tezahür etme": "belirme, görünme",
    "tezat": "karşıtlık, çelişme",
    "teçhiz": "donanım",
    "teşbih": "benzeti, benzetilme",
    "teşebbüs": "girişim",
    "teşekkül": "oluşum",
    "teşerrüf": "onurlanma",
    "teşhir": "gösterme, sergileme",
    "teşhis": "tanı",
    "teşkilat": "örgüt",
    "teşrif": "gelme, onurlandırma",
    "teşrifat": "konukçuluk",
    "teşriki mesai": "işbirliği",
    "teşvik": "özendirme, isteklendirme",
    "ticaret": "tecim, alım satım",
    "timsal": "örnek, simge",
    "tiraj": "baskı sayısı",
    "tirat": "uzun konuşma",
    "tirbuşon": "tıpaçeker",
    "tiryaki": "düşkün",
    "tolerans": "hoşgörü, özür payı",
    "tolk-şov": "çene çalma",
    "tonmayster": "ses yönetmeni",
    "topografya": "yerbetim",
    "trajedi": "ağlatı",
    "trajik": "ağlatısal, çok acıklı",
    "transfer": "taşıma, aktarım",
    "transplantasyon": "aktarım",
    "travma": "vuruk, sarsıntı, örselenme",
    "treking": "doğa yürüyüşü",
    "trent": "akım, eğilim",
    "tribün": "izlenek, sekilik",
    "trotuar": "kaldırım",
    "troyka": "üçlü",
    "tsunami": "süpürtü, deprem dalgası",
    "tuhaf": "alışılmamış, gülünç",
    "tur": "dönü, dolaşı",
    "turist": "gezmen, gezgin",
    "turistik": "gezimsel",
    "turne": "dolaşı",
    "tuş": "dokunaç",
    "töhmet": "suçlama",
    "tövbe": "pişmanlık",
    "tüccar": "tecimen",
    "tüfe": "tüketici eder göstergesi",
    "tümör": "ur",
    "tünel": "örtükgeçit",
    "türbülans": "burgaç",
    "ufki": "yatay",
    "ufuk": "çevren, gözerimi",
    "uhde": "sorumluluk",
    "ukala": "bilgiç, bilecen",
    "ukde": "iç kaygısı",
    "ulema": "din bilgini",
    "ultra": "aşırı",
    "ultrason": "yansılanım",
    "ultrasonografi": "yansılanım aygıtı",
    "ultraviyole": "morötesi",
    "ulvi": "yüce",
    "umum": "kamu, genel",
    "unsur": "öğe",
    "unvan": "ad, san",
    "usare": "özsu",
    "usul": "yöntem, yol, düzen",
    "uzuv": "örgen, üye",
    "vaat": "söz verme",
    "vade": "süre",
    "vadi": "koyak",
    "vahim": "korkunç, korkulu",
    "vahşet": "ürküntü, ürkünç",
    "vahşi": "yabanıl",
    "vaka": "olay, olgu",
    "vakar": "onur, ağırbaşlılık",
    "vaki": "olagelen",
    "vakit": "süre, süreç",
    "vakur": "başıdik",
    "vakıf": "bağış, bırakma, bağlama",
    "vali": "ilbay",
    "valiz": "yol çantası",
    "valör": "geçerlilik",
    "varis": "toplardamar genişlemesi",
    "variyet": "varlık",
    "varoş": "dışyöre",
    "varyant": "değişke, yanbiçim",
    "varyasyon": "değişirlik, çeşitleme",
    "vasat": "orta, ortam",
    "vasati": "ortalama",
    "vasi": "korunman, yerine yetkili",
    "vasiyetname": "kalıtyazı",
    "vasıf": "nitelik, öznitelik, ayırt",
    "vasıl": "erişen, ulaşan, ulama, bağlantı",
    "vasıta": "araç, aracı",
    "vasıtalı": "dolaylı",
    "vasıtasıyla": "eliyle",
    "vatan": "yurt, ülke",
    "vaveyla": "çığlık",
    "vazife": "görev",
    "vaziyet": "duruş, konum",
    "veb": "ağ",
    "vebal": "sorumluluk",
    "vecibe": "koşul, ödev, borç",
    "veciz": "öz, derli toplu",
    "vecize": "özdeyiş, özlü söz",
    "veda": "ayrılık",
    "vefa": "sözünde durma, anılara saygı",
    "vehim": "kuruntu",
    "vekâlet": "yetkili kılma",
    "vekâletname": "yetkilendirme belgesi",
    "velev": "olsa bile, olsa da",
    "velhasıl": "kısaca, sözün özü",
    "veraset": "kalıtçılık, kalıtta hak sahibi olmak",
    "versiyon": "eşiz, eşyazı, uyarlama, sürüm",
    "vesayet": "kısıtlı kişi yöneticiliği, korunmanlık",
    "vesika": "belge",
    "vesile": "nedence",
    "vesvese": "kuşku, işkil, kuruntu",
    "veto etmek": "olmazlamak",
    "veya": "ya da",
    "vibratör": "sarsaç",
    "vicdan": "duyunç, yürekbuyruğu",
    "video": "görüntü alıcı",
    "vilayet": "il",
    "viraj": "dönemeç, sapak, büküm",
    "virman": "aktarım",
    "vitrin": "sergilik",
    "viyadük": "köprü yol, aşıt",
    "vize": "görüldü",
    "vizyon": "görüş, görünüm",
    "vizüel": "görsel",
    "volüm": "ses oylumu",
    "vuku bulmak": "olmak",
    "vukuat": "olaylar, olup bitenler",
    "vâkıf": "bilen, anlayan",
    "vâris": "kalıtçı",
    "yad": "yabancı",
    "yadigâr": "anmalık",
    "yahut": "ya da",
    "yani": "şu demek, diyesim, sizin anlayacağınız",
    "yar": "uçurum",
    "yediemin": "güvenilir kişi",
    "yegâne": "biricik, tek",
    "yeis": "üzüntü",
    "yeknesak": "tekdüze",
    "yekten": "birdenbire",
    "yekûn": "tutar, toplam",
    "yemin": "ant içme",
    "yevmiye": "gündelik",
    "yâd": "hatırlama, anma",
    "yâr": "sevgili",
    "zaaf": "güçsüzlük",
    "zabıt": "tutanak",
    "zafer": "utku",
    "zafiyet": "güçsüzlük",
    "zahiri": "görünen",
    "zalim": "kıyıcı, acımasız",
    "zam": "artırım",
    "zaman": "sürev, sürey, süre",
    "zamir": "adıl",
    "zan": "sanı, kuşku",
    "zanlı": "sanık",
    "zarafet": "incelik",
    "zarar": "dokunca",
    "zarf": "belirteç",
    "zaruri": "kaçınılmaz, zorunlu",
    "zayi": "yitik",
    "zehir": "ağı",
    "zekâ": "kavrama yetisi, anlak",
    "zelzele": "yer sarsıntısı",
    "zemin": "ortam, temel",
    "zengin": "varsıl",
    "zeval": "aşağılama, sona erme",
    "zevk": "beğenç, beğeni",
    "zihin": "bellek",
    "zihniyet": "düşünce yolu, anlayış",
    "zilyet": "iye, elmen",
    "zimmet": "borç",
    "zira": "çünkü",
    "zirve": "doruk, tepe",
    "ziyade": "çok, bol",
    "ziyafet": "şölen",
    "ziyaret": "görmeye gitme",
    "ziynet": "süs, bezek",
    "zorlu": "çekişmeli",
    "zorunlu": "gerekli",
    "zuhur": "ansızın oluverme, görünme",
    "zulüm": "kıygı",
    "zül": "alçalma",
    "zümre": "topluluk, katman",
    "zürriyet": "döl, soy ",
    "zıt": "karşıt, aykırı",
    "âdet": "görenek, alışkı",
    "âlem": "evren, eğlenti, el gün",
    "âli": "ulu, yüce",
    "âlicenap": "iyiliksever, cömert",
    "âlim": "bilgin",
    "âmâ": "görmez",
    "âtıl": "boş durur, işsiz",
    "âşık": "tutkun",
    "çare": "çözge, umar",
    "çaresiz": "umarsız, onulmaz",
    "çek etmek": "yoklamak, denetimlemek",
    "çek": "ödene",
    "çember": "döngü",
    "çerçeve": "kapsamca",
    "çet": "söyleşi, gevezelik",
    "çeync": "akça alım-satımı",
    "çeşni": "tadım",
    "çini": "sırlıtaş",
    "ödem": "şişlik",
    "ömür": "yaşam",
    "örf": "töre, gelenek",
    "ötanazi": "ölmelik",
    "özet ": "sözün özü",
    "özür": "engel, eksiklik",
    "ültimatom": "son uyarı",
    "ümmet": "inandaş topluluğu",
    "üniforma": "birörnek giysi",
    "ünite": "birim, bölüm",
    "üniter": "birleşmiş, bütünbirim",
    "üniversite": "bilimler yurdu",
    "üslup": "biçem, söyleyiş, özanlatı",
    "ütopik": "düşsel",
    "ütopya": "düş, olmazdüş",
    "ırk": "anasoy",
    "ırkiyat": "budunbilim",
    "ırkçılık": "soyculuk",
    "ıslah": "düzeltme",
    "ıslahevi": "eğitme yurdu",
    "ısrar etme": "üsteleme",
    "ıtır": "güzel koku",
    "şaheser": "üstün yapıt, başyapıt",
    "şahika": "doruk",
    "şahit": "tanık",
    "şahsen": "kendi",
    "şahsi": "kişisel, özlük",
    "şahsiyet": "kişilik, özyapı",
    "şahıs": "kişi",
    "şaibe": "kuşku, kir, leke",
    "şair": "ozan",
    "şaki": "yolkesen",
    "şakul": "çekül",
    "şalter": "çevirgeç",
    "şamandıra": "yüzentop",
    "şamil": "kapsayan",
    "şan": "ün",
    "şans": "uğur",
    "şantaj": "karabaskı, gözkorkutum",
    "şantiye": "işlik",
    "şarampol": "yan çukur",
    "şarj": "doldurma, yükleme",
    "şarjör": "yükleyici",
    "şark": "doğu",
    "şart": "koşul, gerekli",
    "şartlı tahliye": "koşullu salıverilme",
    "şartname": "koşulbelge",
    "şasi": "çatkı",
    "şavk": "ışık",
    "şayan": "değer, yakışır, yaraşır",
    "şayet": "eğer, ola ki, olur ki",
    "şayia": "söylenti, duyuk",
    "şaşaa": "gösteriş, görkem, parıltı",
    "şaşırtma": "yanıltı",
    "şebnem": "çiy",
    "şecere": "soysop, soyağacı",
    "şeffaf": "saydam",
    "şefkat": "sevecenlik",
    "şehir": "kent, il",
    "şehvet": "kösnü",
    "şekil": "biçim",
    "şeklen": "biçimce",
    "şema": "çizem, çizenek",
    "şemsiye": "güneşlik",
    "şer": "kötülük",
    "şerait": "koşullar",
    "şeref": "onur, özsevi",
    "şerh": "yorumlama, açımlama",
    "şevk": "istek, sevinç",
    "şey": "nesne",
    "şiar": "yol, iz, belgi",
    "şifa bulma": "onma",
    "şifahi": "sözlü",
    "şifre": "gizyazı",
    "şike": "danışıklı döğüş",
    "şikâyet": "yakınma, sızlanma",
    "şilep": "yük gemisi",
    "şilt": "ödülce",
    "şimal": "kuzey",
    "şimendifer": "demiryolu",
    "şirket": "ortaklık",
    "şive": "ağız, söyleyiş",
    "şizofren": "erken bunama",
    "şofben": "ısıtmaç",
    "şoför": "sürücü",
    "şok": "çarpma, sarsıntı",
    "şoke olmak": "sarsılmak, şaşırmak",
    "şov": "gösteri",
    "show": "gösteri",
    "şovrum": "sergievi",
    "showroom": "sergievi",
    "şu halde": "öyleyse",
    "şua": "ışın",
    "şube": "bölüntü, dal",
    "şura": "danışma kurulu",
    "şuur": "bilinç, us",
    "şuuraltı": "bilinçaltı",
    "şöhret": "ün",
    "şükran": "iyilik bilme",
    "şüphe": "sezik, kuşku",
    "şık": "bölüm, seçenek, yerinde, uygun"
};

/*
 * Kod kalitesi utanç verici. Ama Python'un rahatlığından sonra JavaScript...
 * Bir de projenin ömrü ne olacak belli değil ya, o yüzden çok vakit harcamak
 * istemedim.
 */

function is_letter(str) {
    return str.match(/[a-z]/i);
}

function mark_suggestions() {
    var input = document.getElementById("input").innerHTML; 
    var output = "";

    max_key_len = 20 // Magic number. Hard-coded without shame.

    for (var i=0; i < input.length; i++) {
        var flag = true;
        for (j = max_key_len; flag && j > 1; j--) {
            candidate = input.substr(i, j);
            lowercase = candidate.toLowerCase();

            not_preceded_by_letter = true;
            if (i > 0) {
                prev_char = input.substr(i-1, 1);
                if (is_letter(prev_char)) {
                    not_preceded_by_letter = false;
                }
            }

            if (lowercase in suggestions && not_preceded_by_letter) {
                output += "<a target=\"_blank\" style=\"font-weight: bold; text-decoration: none; color: #000000\" href=\"http://nisanyansozluk.com/?k=";
                output += lowercase + "\" title=\"" + suggestions[lowercase] + "\">" + candidate + "</a>";
                pieces = suggestions[lowercase].split(",")
                for (piece_id in pieces) {
                    s = pieces[piece_id].trim()
                    output += "<a target=\"_blank\" style=\"font-weight: bold; text-decoration: none; color: #4080A0\" href=\"http://nisanyansozluk.com/?k=" + s + "\" title=\"" + s + "\">*</a>";
                }
                i = i + j - 1;
                flag = false;
            }
        }
        if (flag == true) {
            output += input.substr(i, 1);
        }
    }

    document.getElementById("output").innerHTML = output;
}

mark_suggestions()
